### ISSUE TITLE
Cannot resolve all deferred in one Future

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#104]
```
trait DeferredResolver[-Ctx] {
  def resolve(deferred: List[Deferred[Any]], ctx: Ctx): List[Future[Any]]
}
```
should also have this possibility:
```
trait DeferredResolver[-Ctx] {
  def resolve(deferred: List[Deferred[Any]], ctx: Ctx): Future[ListFuture[Any]]
}
```
so that the client can decide to resolve all `Deferred` in one shot (one database query or one http request)

**Comment by OlegIlyenko** [comment]
Do you mean `Future[List[Any]]`? This it was was implemented initially. After some time I noticed, that this approach makes error handing very hard. Sometimes you may have several futures (not nesessarely 1:1 to the number of deferred values) and if you squish them together in future then you loose the ability to have very presice error handing (in cases where several futures fail at the same time for different reasons) and it was an issue before.

Even with the current signature you still have a choice how you handle the deferred resolution. Here is an example that works with just one `Future`, but produces a list of `Future`s:

```scala
case class Article(id: String, name: String)
case class Comment(articleId: String, content: String)

class ExternalService {
  def fetchComments(articleIds: Vector[String]): Future[Vector[Comment]] = ???
}

case class CommentsDeferred(articleId: String) extends Deferred[Seq[Comment]]

class CommentsResolver(service: ExternalService) extends DeferredResolver[ExternalService] {
  def resolve(deferred: Vector[Deferred[Any]], ctx: ExternalService) = {
    val articleIds = deferred map {case CommentsDeferred(id) => id}

    val comments: Future[Vector[Comment]] =
      ctx.fetchComments(articleIds)

    val commentsByArticle: Future[Map[String, Vector[Comment]]] =
      comments.map(_.groupBy(_.articleId))

    articleIds map (articleId =>
      commentsByArticle.map(_.getOrElse(articleId, Nil)))
  }
}
```

Do you think ithis kind of approach would be also suiatble in your case?

**Comment by yanns** [comment]
Yes I mean `Future[List[Any]]`.

I understand your example. But I have the feeling it makes the implementation more difficult that it should be.
When the database delivers a `Future[List[A]]`, then either it is successful or not. The error handling is quite trivial in that case... ;) Maybe we should make this easy to implement.

**Comment by OlegIlyenko** [comment]
That's true, in some concrete situations the implementation of deferred resolver may be harder than it possibly can be for this case. But `DeferredResolver` is intended as a generic mechanism for different use-cases which is able to provide the most precise error-handling for all of them.

Not to mention, that `DeferredResolver` is pretty low level mehanism. I can definitely see more higher level (use-case driven) helpers build on top of `DeferredResolver`. One also need to be very cautious in the implementation since deferred values more often than not contain duplicates. So they need to be deduplicated before making a DB query. DB query results on the other hand can't be returned as-is (in most cases), because the shape of the result should reflect 1:1 the shape of `deferred: Vector[Deferred[Any]]`. Not to mention that `deferred: Vector[Deferred[Any]]` normally will contain `Deferred` values of different types, so you most probably will end up with several futures anyway.

**Comment by yanns** [comment]
OK I understand.
From the signature, it's not clear that the 2 lists are so deeply linked.
To make it clearer, maybe the signature could be:
```
def resolve(deferred: List[Deferred[Any]], ctx: Ctx): List[Future[(Deferred[Any], Any)]]
```
What do you think?

**Comment by yanns** [comment]
I close this issue as the initial request is clearly explained.

**Comment by OlegIlyenko** [comment]
It sounds very good. `List[Future[(Deferred[Any], Any)]]` sounds also much more intuitive to me and immediately hints about the shape of the result. Under normal circumstances I wouldn't think twice about it's inclusion, but in this case it's a bit different. In my opinion this is a performance critical place which was designed to provide an optimization. Because of this I really would like to avoid unnecessary boxing if possible. 

That said, I will think again about the signature of resolve method, I like it `List[Future[(Deferred[Any], Any)]]` a lot :)
