### ISSUE TITLE
How to properly flow arguments to sub-queries? 

### ISSUE THREAD

**Issue by luminescent** [sangria-graphql/sangria#107]
Hi 

I have a situation where retrieving a subnode needs an argument passed to the parent node. I am not sure how to implement this properly. I have basically blended the concepts of a context, state and repository in one thing to achieve this and would like to know if there's a better way of doing it. 

Here is my schema: 
```
root(criteria) {
  property0
  detail {
    property0
    innerMostDetail {
      property0
    }
  }
}
```

Retrieving a `root` node requires passing in a mandatory `criteria` parameter. Retrieving the `detail` is done by `root.property0` and retrieving `innerMostDetail` is done by passing in `criteria` (so the root argument) and the `detail.property0`. 

My code is as follows (I started from the StarWars example): 

```scala
object SchemaDefinition {
  
  val CriteriaArg = Argument("criteria", StringType, description = "criteria")
  
  val InnerMostDetailType = ObjectType(
    "innerMostDetail", 
    fields[Unit, InnerMostDetail](
      Field("property0", StringType, resolve = _.value.property0)
  ))
  
  val DetailType = ObjectType(
    "detail",
    fields[ContextAndRepo, Detail](
      Field("property0", StringType, resolve = _.value.property0),
      Field("property1", StringType, resolve = _.value.property1),
      Field("innerMostDetail", OptionType(InnerMostDetailType),
        resolve = c ⇒ Future { c.ctx.getInnerMostDetail(c.ctx.Criteria.get, c.value.property0)})
    ))
  
  val RootType = ObjectType(
    "root",
    fields[ContextAndRepo, Root](
      Field("property0", StringType, resolve = _.value.property0),
      Field("detail", OptionType(DetailType), resolve = c ⇒ Future { c.ctx.getDetail(c.value.property0) })
    )
  )
  
  val Query = ObjectType(
    "Query",
    fields[ContextAndRepo, Unit](
      Field("root", RootType,
        arguments = CriteriaArg :: Nil,
        resolve = (ctx) => {
          ctx.ctx.Criteria = Some(ctx arg CriteriaArg)
          ctx.ctx.getRoot(ctx arg CriteriaArg)})
    ))  

  val TheSchema = Schema(Query)
  
}

class ContextAndRepo {
  
  var Criteria: Option[String] = None

  def getRoot(criteria: String): Root = {
    Root(s"Root property 0 for $criteria", None)
  }
  
  def getDetail(property0: String): Detail = {
    Detail(s"Detail property 0 for $property0", "Detail property 1", None)
  }
  
  def getInnerMostDetail(criteria: String, property0: String): InnerMostDetail = {
    InnerMostDetail(s"Inner most detail property0 for criteria $criteria and property $property0; global criteria is $criteria.")
  }
}

```

It works but there are a few problems with it: 
*  not sure it is actually thread - safe; do we get an instance of ContextAndRepo created each time a root query is requested?
*  the ContextAndRepo class is sort of hideous, as it blends together state and data retrieval and I would like these to be separate, has that mutable member etc; 
*  I have seen the UpdateCtx example from the documentation but I did not fully understand it; at its very core it seems like it's essentially doing what I am doing, decorating the context object with some state (though at least everything there is still immutable).  

What is the proper way of solving this in Sangria? 

Thank you!

**Comment by OlegIlyenko** [comment]
Thanks a lot for the detailed description!

> not sure it is actually thread - safe; do we get an instance of ContextAndRepo created each time a root query is requested?

You are always in control of `ContextAndRepo` instance creation. When you execute query (with `Executor.execute`, for instance) you need to provide a `userContext` instance, which then would be used during a whole query execution. So if somebody will ask for a `root` field several times:

```js
query Foo {
  r1: root(criteria: "criteria1") {...}
  r2: root(criteria: "criteria2") {...}
}
```

then you will have a race condition, so it is not thread-safe. I would discourage mutable approach in this case. As you mentioned, `UpdateCtx` can be used to solve this in an immutable way. It was designed specifically for these kind of use-cases. Below  I added an example of how you can use it.

> the ContextAndRepo class is sort of hideous, as it blends together state and data retrieval and I would like these to be separate, has that mutable member etc;

I agree, it mixes up a lot of concerns. The user context in general is designed to provide all necessary helpers for query to execute. So if your schema has different, but interdependent concerns, than you will need a place to pack them together. I personally would extract business logic out of the context though. Something like this:

```scala
case class QueryContext(service: SomeService, criteria: Option[String] = None)

class SomeService {
  def getRoot(criteria: String): Root = {
    Root(s"Root property 0 for $criteria", None)
  }

  def getDetail(property0: String): Detail = {
    Detail(s"Detail property 0 for $property0", "Detail property 1", None)
  }

  def getInnerMostDetail(criteria: String, property0: String): InnerMostDetail = {
    InnerMostDetail(s"Inner most detail property0 for criteria $criteria and property $property0; global criteria is $criteria.")
  }
}
```

This makes it much easier, for instance, to test `SomeService` independently of everything else. It also makes `QueryContext` simple, logic-less and immutable case-class. 

If at some point you will have a lot of independent concerns inside of a context, than I would suggest  to split it in a spirit of cake pattern. I even created a simple test case to demonstrate this approach:

https://github.com/sangria-graphql/sangria/blob/master/src/test/scala/sangria/execution/ContextPassingSpec.scala

Here is an example of how you can use `UpdateCtx` and `QueryContext` (with some minor adjustments to other types as well):

```scala
object SchemaDefinition {
  val CriteriaArg = Argument("criteria", StringType, description = "criteria")

  val InnerMostDetailType = ObjectType(
    "innerMostDetail",
    fields[Unit, InnerMostDetail](
      Field("property0", StringType, resolve = _.value.property0)
    ))

  val DetailType = ObjectType(
    "detail",
    fields[QueryContext, Detail](
      Field("property0", StringType, resolve = _.value.property0),
      Field("property1", StringType, resolve = _.value.property1),
      Field("innerMostDetail", OptionType(InnerMostDetailType),
        resolve = c ⇒ Future {
          c.ctx.criteria map (c.ctx.service.getInnerMostDetail(_, c.value.property0))
        })
    ))

  val RootType = ObjectType(
    "root",
    fields[QueryContext, Root](
      Field("property0", StringType, resolve = _.value.property0),
      Field("detail", OptionType(DetailType), resolve = c ⇒
        Future { c.ctx.service.getDetail(c.value.property0) })
    )
  )

  val Query = ObjectType(
    "Query",
    fields[QueryContext, Unit](
      Field("root", RootType,
        arguments = CriteriaArg :: Nil,
        resolve = c ⇒ {
          val criteria = c arg CriteriaArg

          UpdateCtx(c.ctx.service.getRoot(criteria))(_ ⇒
            c.ctx.copy(criteria = Some(criteria)))
        })
    ))

  val TheSchema = Schema(Query)
}
```

`UpdateCtx` has following structure: 

```scala
UpdateCtx(someValueAction)(resultOfAction ⇒ newUserContext)
```

normally you return an `Action` from a resolve function. `UpdateCtx` wraps this action and allows you to "map" the user context too, as soon as action produces some value (for example when `Future` value is arrived).

In the example though, we don't really need to know the value in order to create new `QueryContext` for a nested child fields, so we just ignore it. Since it's immutable now, you don't have a race condition anymore: every `root` field execution inside of one query gets it's own copy of `QueryContext`.

Hope this helps :)

**Comment by luminescent** [comment]
This works perfectly, Oleg, thank you for the solution and the pointers.

**Comment by JeetuChoudhary** [comment]
What is Root and Detail?
