### ISSUE TITLE
Projector and case classes

### ISSUE THREAD

**Issue by vhiairrassary** [sangria-graphql/sangria#127]
First, 👍 for the project and code quality !

We are evaluating Sangria on top of a RDBMS and considering the following schema:
```scala
val CommentType = ObjectType("Comment", fields[Unit, Comment](
    Field("id", StringType, resolve = _.value.id),
    Field("content", StringType, resolve = _.value.content)
))

val QueryType = ObjectType("Query", fields[ExternalService, Unit](
    Field("comments", ListType(CommentType), resolve =
        Projector((ctx, f) => {ctx.ctx.fetchComments}))
))
```

To perform efficient projections we are trying to use a `Projector`, but since `fetchComments` has to return `Comment` instances what should `fetchComments` return if the only requested field is `id` ? Should we return a `Comment(id = 11, comment = null)` ? 

Thanks you in advance

**Comment by OlegIlyenko** [comment]
It's always hard with projections since by definition they may violate constraints of the domain model (e.g. mandatory fields suddenly disappear). 

`Comment(id = 11, comment = null)` is definitely a possibility. I guess it depends on how you handle DB results and deserialize them into case classes, and which tradeoff are you willing to take. 

We also use this feature to make MongoDB projections. But in out case we decided to work with raw `DBObject` that comes from mongo driver. So in our case `Comment` GraphQL type would be defined like this `val CommentType = ObjectType("Comment", fields[Unit, DBObject](...))` (in other words we don't use a `case class` to define this GraphQL type).

**Comment by damirv** [comment]
Interesting discussion/question. @OlegIlyenko just asking out of curiosity: do you work all the way through with DBObject's in your scala code or do you convert them at some point to case classes?

**Comment by OlegIlyenko** [comment]
At the moment we are using our domain model for main/exposed GraphQL schema. But we are currently experimenting with projection and there is additional/experimental GraphQL schema that works exclusively with `DBObject` and `JObject` (which come from MongoDB and Elasticsearch). It helps a lot to improve performance.

**Comment by vhiairrassary** [comment]
Great, we will have try to perform the request using slick and then transform the result set as a `spray.json.JsValue`.

Thank you for the answers.

**Comment by nlhkh** [comment]
@vhiairrassary how can you be selective which fields to fetch with Slick? Do you use plain SQL?

**Comment by vhiairrassary** [comment]
@nlhkh Yes I use plain SQL

**Comment by mingzhou** [comment]
@nlhkh @vhiairrassary  Did you find a solution to project fields using Slick and GraphQL? Thanks.

**Comment by vhiairrassary** [comment]
You have to use [plain SQL queries from Slick](http://slick.lightbend.com/doc/3.2.1/sql.html).
