### ISSUE TITLE
Akka Cluster with Sangria 

### ISSUE THREAD

**Issue by JeetuChoudhary** [sangria-graphql/sangria#170]
I want to create Akka Cluster on my sangria project.

Any Suggestion how can i do this?
Thanks

**Comment by OlegIlyenko** [comment]
Using akka with Sangria should be pretty straightforward. I know that some users do use them together including myself. Though It's hard for me to give more specific answer since the question is very broad and you haven't provided many information about an application you are building. Equipped with this information, I can narrow down a set of possible solution to (hopefully) a small subset which is particularity suitable for your application.

I can also suggest you to check out the ["ask" pattern](http://doc.akka.io/api/akka/2.0/akka/pattern/package.html) since it help with integrating akka actors with sangria's resolve functions.

Since the topic is very broad I would suggest to move this discussion in the Gitter chat: https://gitter.im/sangria-graphql/sangria. I think GitHub issues are very good for more narrow topics and specific issues/feature requests/ideas. Chat or [mailing list](https://groups.google.com/forum/#!forum/sangria-graphql), on the other hand, fits very well for a lengthy discussions or Q/A sessions.

**Comment by JeetuChoudhary** [comment]
thanks, I will keep that in mind next time
