### ISSUE TITLE
DefaultChanged may be a breaking change

### ISSUE THREAD

**Issue by cjoudrey** [sangria-graphql/sangria#174]
While porting `SchemaComparator` over to `graphql-ruby` I noticed `sangria` currently does not consider `DirectiveArgumentDefaultChanged`, `InputFieldDefaultChanged`, and `ObjectTypeArgumentDefaultChanged` as breaking changes.

_Before_

```
type A {
  A(B: Int! = 1): String
}
```

_After_

```
type A {
  A(B: Int!): String
}
```

I believe in this case removing the default value is a breaking change as you could previously omit `B`.

**Comment by OlegIlyenko** [comment]
Hmmm... I'm pretty sure that following definition is not allowed:

```graphql
type A {
  A(B: Int! = 1): String
}
```

because `B` is not-null. This means that user always much provide this argument, thus the default value would never be used.

Here is a small bit of evidence. When I do it with graphql-js and try to use this field without providing an argument, I get following result:

```json
{
  "message": "Field \"A\" argument \"B\" of type \"Int!\" is required but not provided.",
  "locations": [
    {
      "line": 4,
      "column": 7
    }
  ]
},
```

In sangria I even have an invariant for this, so this throws an exception at schema definition time.

If you try to do the same with query variables, e.g:

```graphql
query Foo($id: ID! = "bar") {
  film(id: $id) {title}
}
```

The you will get:

```json
{
  "errors": [
    {
      "message": "Variable \"$id\" of type \"ID!\" is required and will not use the default value. Perhaps you meant to use type \"ID\".",
      "locations": [
        {
          "line": 1,
          "column": 22
        }
      ]
    }
  ]
}
```

**Comment by cjoudrey** [comment]
Thanks for the reply. I had no idea that's how default value worked with `!`.

It'll be interesting to see if this behaviour changes now that we have `null` literals.
