### ISSUE TITLE
Indicate to a Fetcher/DeferredResolver that value is missing

### ISSUE THREAD

**Issue by phuu** [sangria-graphql/sangria#192]
In a deferred lookup, how can I indicate to the Fetcher that the requested value is missing?

Ideally, given user IDs `[a, b, c]`, where `b` does not exist, I'd like to return `List[Option[User]]` like `[Some(A), None, Some(c)]`.

Is this possible now? I guess I could just return a null value?

And if I use an `Option`, how does this relate to the `HasId` implicit?

**Comment by OlegIlyenko** [comment]
At the moment, you can use `fetcher.deferSeqOpt(List("a", "b", "c"))` which will result in following array result:

```json
["A", "C"]
```

In your use-case, do you want it to produce following JSON array?

```json
["A", null, "C"]
```

It was an explicit decision to flatten the result list with `deferSeqOpt`, because it is a very common use-case. I think it would be pretty trivial to add a variation of `defer` that returns `List[Option[T]]` which results in `["A", null, "C"]`. So let me know whether you have this use-case, and I can add support for it (of if you would like to create a PR, I would be happy to merge it).

Of course, by implementing `DeferredResolver` from scratch you can achieve the same result, but I think it would better to enhance the Fetch API if there is a use-case for it.

**Comment by phuu** [comment]
I mean when passing returning from the Fetcher's internal value resolution method. The docs say...

>  It is important to note, that the resulting list must have the same size. This allows an executor to figure out the relation between deferred values and results. The order of results also plays an important role.

... so I figured I had to do the same with a Fetcher. Do I? Or does Sangria use `HasId` internally to figure this out?

**Comment by OlegIlyenko** [comment]
I see. No, this requirement is only valid for `DeferredResolver` (it is more low-level API, so it relies on a specific contract rather than a type system for performance reasons). As you pointed out, Fetch API uses `HasId` type class to match the entities, so the restriction does not apply here. I probably should clarify it in the docs as well :)

**Comment by phuu** [comment]
Cool! That would be really useful, thanks :)

**Comment by phuu** [comment]
(While you're there, is `DeferredResolverp` a typo?)

**Comment by OlegIlyenko** [comment]
Fixed 👍  https://github.com/sangria-graphql/sangria-website/commit/06dfc7d7c2046789b34bf7e05bd93c86cd416881

**Comment by phuu** [comment]
Ace. Thanks.

**Comment by mikaelstaldal** [comment]
I have run into the same issue, I need to report a missing value to the Fetcher.

I cannot use `Fetcher.deferSeqOpt`, since I am not returning a sequence to the client. I return single optional entities at various places of the result, and I want to use Fetcher to batch and optimize fetching of them from backend data store.

It would be useful for me if Fetcher supported this.

(I don't understand how `Fetcher.deferOpt` can be used).

**Comment by OlegIlyenko** [comment]
@mattfenwick `Fetcher.deferOpt` sounds like a perfect fit for your use-case.

Let me show how it work in more detail:

1. As query execution goes, different fields return different values. Let's say they have returned following deferred values: 
  * field `A`: `fetcher.deferOpt(1)`
  * field `B`: `fetcher.deferOpt(123)`
  * field `C`: `fetcher.deferOpt(Some(10))`
  * field `D`: `fetcher.deferOpt(Node)`
  * field `E`: `fetcher.deferOpt(123)`
  * field `E`: `fetcher.deferOpt(2)`
2.  Deferred resolver kicks in at some point, gets all these deferred values and calls fetcher with: `fetcher.fetch(someCtx, Seq(1, 123, 10, 2))`
3. Fetcher gets these values, loads objects from some place and returns following results: `Future.successful(Seq(Article(10, "foo"), Article(123, "bar")))`
4. Execution engine recieves these values and finishes field resolution with following values:
  * field `A`: `None`
  * field `B`: `Some(Article(123, "bar"))`
  * field `C`: `Some(Article(10, "foo"))`
  * field `D`: `None`
  * field `E`: `Some(Article(123, "bar"))`
  * field `E`: `None`

Let me know if you have further questions.

**Comment by mikaelstaldal** [comment]
Yes, that works. Thanks!
