### ISSUE TITLE
Analyse query without execution

### ISSUE THREAD

**Issue by tgvashworth** [sangria-graphql/sangria#195]
I'd like to be able to analyse queries without actually executing the query, so that I can build a "stored query" system that checks queries before storing them.

For example, I'd like to be able to return a `400 Bad Request` to a query that will exceed the maximum complexity, or that uses unknown fields.

Queries would be submitted without `variables` or `operationName` present.

Does this sound possible? I guess the main problem is that you need variables present to properly analyse the the query.

**Comment by OlegIlyenko** [comment]
Thanks for opening this topic! I think the workflow you have described has a lot of value, It should be possible to implement it, at least in terms of validations. For example, you can validate query independently from execution and then execute the query with disabled validations to save some CPU cycles.

You are right about query reducers, though. At the moment they are implemented in such a way, that they require `variables` and `operationName` to be present in order to make the analysis. So it analyses the actual execution path. This approach has a number of advantages but also means that query cannot be analyzed in isolation.

I think it would be a very interesting to implement a more lightweight version of query reducer that only considers info contained in the query for every available operation. This means that if one uses the variables for things like max number of results in a list, then there should be a way to handle these fields and consider the worst-case scenario.

I think it will require quite a bit of work, so I think this feature would be a good candidate for inclusion in one of the 1.x versions. What do you think? How critical is this feature for you right now?

**Comment by phuu** [comment]
That's sounds great, and no, it's not critical right now — I just submitted the issue to get things moving and check it was possible. I'd be more than happy to work on some parts of this change too. 

Would a possible first step be allow checking for unknown fields, as that doesn't require `variables`?

**Comment by OlegIlyenko** [comment]
Great! I would be happy to accept contributions!

Sure thing, you can validate query like this:

```scala
val violations = QueryValidator.default.validateQuery(schema, queryDocument)
```

for this you don't need variables. And it will run all available GraphQL validation against this query and give you back a list of violations (validation errors). You can also pick and choose which validations you want to use if you don't want to validation query against them all.

**Comment by phuu** [comment]
Oh cool! I'll give it a try.

**Comment by OlegIlyenko** [comment]
@phuu Recently I was researching a possibility of making query reduces usable standalone. but then I realized that you can actually already achieve something very similar with `Executor.prepare`. I added this approach in the docs:

http://sangria-graphql.org/learn/#verification-with-query-reducers

**Comment by phuu** [comment]
Neat!

I don't think this will work for my particular case becuase I'm accepting arbitrary queries, so I'd have to extract any variables used in the query and generate safe dummy values based on type. Not impossible, and I suspect it would be useful functionality to have for generative testing!

**Comment by OlegIlyenko** [comment]
I believe that it is now made possible in https://github.com/sangria-graphql/sangria/issues/277. I will close it for the moment being, but please feel free to reposen this issue if something else comes up.
