### ISSUE TITLE
Disable introspection query

### ISSUE THREAD

**Issue by phuu** [sangria-graphql/sangria#211]
I'd like to be able to prevent an introspection query being run. Is there a way to do this? If not, is it something you'd be open to adding?

My use case is a safety feature to prevent leaking information about the  available schema to potential attackers.

I'd like to be able to put some specific logic around disabling the query so that a user in privileged environment, or with elevated permissions, could still run it.

What do you think?

**Comment by OlegIlyenko** [comment]
Sounds like a very good idea, especially for production! In fact, it is already possible to do through middleware and query reducers. Their execution works for introspection parts of the schema just like for any other types and fields. In order to make it a bit more convenient, I just added these helpers:

https://github.com/sangria-graphql/sangria/commit/fd0f271a89b56867a62a1851fca1b64ca67f0cd0

So for example, you can add following logic in the middleware:

```scala
def beforeField(queryVal: QueryVal, mctx: MiddlewareQueryContext[SecureContext, _, _], ctx: Context[SecureContext, _]) = {
  if (ctx.isIntrospection && !ctx.ctx.isUserAllowedToSeeIntrospection) {
    throw new AuthError("You are not allowed to see introspection!")
  } else continue
}
```

I also thinking about adding query analyzers in future. They would kind of fusion between query reducer and validator (examples: `QueryAnalyser.findDeprecated(schema, query)`, `QueryAnalyser.hasIntrospection(schema, query)`, etc.).

**Comment by OlegIlyenko** [comment]
Just added a query reducer for this as well: https://github.com/sangria-graphql/sangria/commit/cac8c8b9dafbb2b00e90220dff87b165319739c3

**Comment by phuu** [comment]
Oleg this is *amazing* work — thanks so much for the fast response and for creating those helpers. They'll be really useful!

🚀

**Comment by meddulla** [comment]
I wanted to limit maxDepth but only if it wasn't an introspection query (it requires greater depth than I wanted to allow). There's probably a much better way but I couldn't compose those query reducers. Anyway came up with this:

```
private def hasIntrospection(rawQuery: String) = {
    val introspectionTypes: Vector[String] = introspection.IntrospectionTypesByName.keys.toVector
    introspectionTypes.map(d => if (rawQuery.contains(d)) 1 else 0).toList.contains(1)
  }
private def rejectDepthExceptIntrospection(queryAst: Document): QueryReducer[DAOContext, DAOContext] = {
    val rawQuery = queryAst.source.get
    val hasIntro = hasIntrospection(rawQuery)
    measureDepth[DAOContext]((depth, ctx) ⇒
      if (depth > queryMaxDepth && !hasIntro) throw MaxQueryDepthReachedError(queryMaxDepth) else ctx)
  }
private def executeQuery(queryAst: Document, vars: Option[JsObject], operation: Option[String]) = {
    Executor.execute[DAOContext, Unit, JsObject](schema, queryAst, new DAOContext,
      [...]
      queryReducers = List(
        rejectDepthExceptIntrospection(queryAst)
      ))
      .map((d: JsValue) => Ok(d))
      [...]
  }
```
If there's a cleaner way to do this, please share. Otherwise, hope it helps!

**Comment by OlegIlyenko** [comment]
@meddulla I would suggest you to implement a new query reducer that just ignores introspection branches of the query. You can take `MeasureQueryDepth` query reducer as a base, and then just customize it a bit:

https://github.com/sangria-graphql/sangria/blob/5f6279b4a810b3674f53d579e43897c48de590bc/src/main/scala/sangria/execution/QueryReducer.scala#L109-L139

This will give you more accurate results. In `reduceField` you can use function `sangria.introspection.isIntrospection(parentType, field)` to determine whether particular field is an introspection field.
