### ISSUE TITLE
Allow numeric fields

### ISSUE THREAD

**Issue by jocelyn-hutin** [sangria-graphql/sangria#213]
Hi,

We are facing an issue with Sangria while trying to match the schema to our API.

Our API return something looking like that :
>{
  "1": [ ... ],
  "2": [ ... ],
  "3": [ ... ]
}

We would like our schema (queries and results) to keep the same format.

But Sangria disallows using numbers has field name, both in the schema and in the query parser.
(more generally, anything starting with a number, which, I know, is a standard in most language).

Tinkering in Sangria's code, I was able to lift this restriction, without any visible negative impact. 

But, the reason to this limitation being unclear to me, I would like to bring the issue here first.
Could you remove this restriction or provide a workaround ?

**Comment by OlegIlyenko** [comment]
I afraid this limitation comes from graphql specification itself. Since sangria is implementation of the spec, I don't think I can do much about it: https://facebook.github.io/graphql/#sec-Names

If you have compelling reasons to remove this limitation I would suggest to raise an issue on the main GraphQL spec repo: https://github.com/facebook/graphql/issues (it already has several issues to relax the name character set restrictions)

**Comment by jocelyn-hutin** [comment]
I see. Shame on me for not reading that part of the spec before hand :)
We'll either try and change our output or bring the issue to GraphQL directly.

In the mean time, I shall close this issue.

Thanks and have a good weekend.
