### ISSUE TITLE
deriveInputObjectType should handle Optional values

### ISSUE THREAD

**Issue by apatzer** [sangria-graphql/sangria#224]
If I have a class with an Option in it, even if that option is a scalar value, I seem to have to redefine it to "help" the deriveInputObjectType macro:

```
case class A(id: Int, b: Option[Int] = None)
implicit lazy val AType: InputObjectType[A] = deriveInputObjectType[A](
  ReplaceInputField("b", InputField("b", OptionInputType(IntType))))
```

Otherwise I get the error:
`Type Option[Int] cannot be used as a default value`

Is there something I am doing wrong here? Why can't the deriveInputObjectType seem to handle Option[_] values the way that deriveObjectType does?

**Comment by OlegIlyenko** [comment]
For optional values, you can just skip `= None` and it will work as intended. Because of the way default values are implemented in scala and sangria, it is not always possible to use the default value provided in a signature. For these cases, I would suggest to provide a default value via `@GraphQLDefault` compile-time annotation. It's also possible that you would need to use `ScalaInput.scalaInput` (e.g. `@GraphQLDefault(scalaInput(FooBar(1, ,"foo")))`) for more complex defaults.

This part of the library is not very well documented, I believe. I will try to improve the docs for it. At some point, I also wanted to revisit the handling of default values and see how it can be improved

**Comment by apatzer** [comment]
As mentioned in the sangria-play-json repository, Play 2.6 now supports default values. Perhaps Sangria could follow a similar approach https://github.com/playframework/play-json/pull/17

Let's say you want to have a single case class represent your GraphQL ObjectType, InputObjectType, and database object. This is super convenient since it does not involve having three separate classes that are "almost" the same. We've all been there and it's a pain to maintain when a new column/field needs to be added.

```
case class DbObject(id: Option[Long] = None, content: String, created: DateTime = DateTime.now)
object DbObject {
   // With Play 2.6, input can be as simple as { "content": "foo" } and 'id' and 'created' will be filled in
   implicit val jsonFormat = Json.using[Json.WithDefaultValues].format[Vitals]

   // Works perfectly
   implicit val dbObjectType = deriveObjectType[Unit, DbObject]()

   // But, Sangria will throw a warning that Option[Long] cannot be used as a default value
   implicit val dbInputObjectType = deriveInputObjectType[DbObject]()
}
```

You can remove the Option[Long] = None and the deriveInputObjectType works...but then the JSON Reads won't be able to handle input like { "content": "foo" } which you'd like for an input, as the DB id is not yet set/generated.

At present, the only possibility that compiles is to redefine the field:
```
implicit val dbInputObjectType = deriveInputObjectType[DbObject](
   ReplaceInputField("id", Field("id", OptionInputType(LongType)))
)
```

**Comment by OlegIlyenko** [comment]
I definitely think that this is a good idea. There is a technical limitation though that makes it hard to achieve. 

Play-json actually creates new instances of objects, which means it's able to access the default value. It comes back to a way default values are encoded by scala compiler. All default values are just methods either on companion object or the actual instance of a class in question. This means that you need an instance of this class in order to discover and analyze the default value.

For input objects, `deriveInputObjectType` does not create new instances of this class. It actually needs all of the information to be available statically at compile time in order to generate a correct GraphQL schema. So it's not always possible to get a default value inside of the macro.

 Regarding some of the points that you have mentioned:

* `id: Option[Long] = None` should work out-of-the-box with both play-json and sangria
* In `created: DateTime = DateTime.now`,  `DateTime.now` would be ignored by sangria, but you can still provide a default value  with:

  ```scala
  import sangria.marshalling.ScalaInput._

  ..., @GraphQLDefault(scalaInput(DateTime.now)) created: DateTime = DateTime.now)
  ``` 

  it does not look very clean, but it still provides this possibility. I think this definition should work with both play-json & sangria.

**Comment by OlegIlyenko** [comment]
On a second thought, `DateTime.now` default value is probably a bad idea for a GraphQL field. GraphQL fields (including their default values) are discoverable via introspection API. It would be very confusing to an end user to see a different default every time server restarts or introspection query is executed. `DateTime.now` is a function/logic, but GraphQL default values should be static data structures which don't change over time.

**Comment by OlegIlyenko** [comment]
I will close this issue for the moment being due to inactivity and is the technical limitation technical limitation mentioned in previous comment. Please feel free to reopen this issue if you would like to continue this discussion.
