### ISSUE TITLE
Denial of service attack

### ISSUE THREAD

**Issue by daliwali** [sangria-graphql/sangria#226]
It was very easy to craft a query that caused the playground to crash. It seems that this query took over 25 seconds to respond to, and the content of the response seems to be 18 MB (!)

```
query HeroAndFriends {
  hero {
    name
    friends {
      friends {
        friends {
          friends {
            friends {
              friends {
                friends {
                  friends {
                    friends {
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Subsequent queries result in `503 Service Unavailable`. 

Another worrying point is that there seem to be just a few unique characters, which are embedded recursively in the response. They could have been de-duplicated to avoid such a massive response.

**Comment by OlegIlyenko** [comment]
Thanks for the feedback, Dali! The main purpose of  [sangria-playground](http://try.sangria-graphql.org/) is to serve as a demonstration and help for people who are just starting with GraphQL and would like to learn basics on how to define a GraphQL schema and integrate it with Playframework. You also need to consider that application is deployed on a smallest free heroku node. So I would like to kindly ask you not to DDOS it :) 

For production-grade setup, I would recommend you to implement safety mechanisms, like [query complexity analysis](http://sangria-graphql.org/learn/#query-complexity-analysis), especially if you would like to expose GraphQL endpoint publically. To follow my own advice, I just added it in the playground as well. So now you will get an error if you try to execute very expensive queries, like the one you have shown in your example.

> Another worrying point is that there seem to be just a few unique characters, which are embedded recursively in the response. They could have been de-duplicated to avoid such a massive response.

Indeed, this is a concern, but this property is inherent to GraphQL specification. Since sangria is a spec-compliant GraphQL implementation, it inherits this behavior as well. If you would like to suggest an improvement, I would encourage you to create a [new issue in graphql repo](https://github.com/facebook/graphql/issues/new). I would also suggest you to check out [falcor](https://netflix.github.io/falcor/) and [JSON Graph](https://netflix.github.io/falcor/documentation/jsongraph.html). If de-duplication of a result is important for your application, then maybe JSON Graph would be a better fit.

**Comment by daliwali** [comment]
Thanks for the response. I tried again with a similar query:

```
query HeroAndFriends {
  hero {
    name
    friends {
      friends {
        friends {
          friends {
            friends {
              friends {
                friends {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

The response payload is ~160kb, and waited for over 2 seconds to reply. I think this has high server cost, low availability, and low bandwidth.

I wasn't aware that response format is mandated by the GraphQL spec. FYI, web standards have an approach to de-duplicating graphs: https://www.w3.org/TR/json-ld/#named-graphs

**Comment by benwilson512** [comment]
@daliwali Is this is an issue with sangria or just a general criticism of GraphQL? If the former, you may want to avoid using public playgrounds on heroku as a benchmark of a technology. If the latter this may not be the most useful location for it.

**Comment by daliwali** [comment]
The former, actually, but you can see how GraphQL's format makes the problem apparent. I noticed that taking seconds to query for 4 objects shouldn't be the case.

In a production environment an accidental query that ends up being more complex than expected could cause downtime. I must stress that the problem is *not about the hosting environment*, but rather how no effort is made to actually optimize DB querying.

I suggest that IDs should be memoized during a query and checked whether it has already been looked up within the same query to avoid unnecessary reading from disk multiple times. Or you can just ignore constructive criticism.

**Comment by OlegIlyenko** [comment]
> but rather how no effort is made to actually optimize DB querying

I would appreciate if you could elaborate on this statement and maybe provide some context. Are you talking about specific service you have in production?

> I suggest that IDs should be memoized during a query and checked whether it has already been looked up within the same query to avoid unnecessary reading from disk multiple times.

If I understand your suggestion correctly, then this feature is already provided by sangria. I would recommend you to check the documentation of Fetch API ("Caching" subsection):

http://sangria-graphql.org/learn/#high-level-fetch-api

> Or you can just ignore constructive criticism.

I don't find this statement constructive :) If you believe that particular point, that you have raised, is being ignored, I would appreciate if you could repeat it and maybe describe it in more detail and how it relates to sangria implementation.

**Comment by daliwali** [comment]
Can we agree that taking seconds to get 4 objects back is a indicative of a performance problem? In an optimized implementation, it wouldn't take much longer to respond with 4 objects no matter how it is formatted, but the difference is orders of magnitude. Look, I don't want to belabor this point to you, have fun.
