### ISSUE TITLE
ObjectTypeDefinition missing interface when interface is defined via extend

### ISSUE THREAD

**Issue by Stowe4077** [sangria-graphql/sangria#267]
If you declare a type and then later extend that type by adding an interface via extend, the added interface is not part of the ObjectTypeDefinition passed along to resolveField in DefaultAstSchemaBuilder (e.g. the definition.interfaces is empty). Further up the call chain, it DOES appear that the added interface is in the interfaces List passed to buildObjectType, but it is NOT in the ObjectTypeDefinition.   Example below (sorry for the System.outs.....but it should show the issue) will output
```
Foo has declared interfaces in buildObjectType of: 
Foo has a list of interfaces in buildObjectType of: HasBaz
Foo has declared interfaces in resolveField bar of: 
Foo has declared interfaces in resolveField baz of: 
```

```
      val basicSchema =
        """
          |schema {
          | query: FooQuery
          |}
          |
          |type FooQuery {
          | foo: Foo
          |}
          |
          |type Foo {
          |   bar: String
          |}
          |
          |interface HasBaz {
          | baz: String
          |}
          |
          |extend type Foo implements HasBaz{
          | baz: String
          |}
        """.stripMargin

      val document = QueryParser.parse(basicSchema).get

      def resolve(context: Context[Unit, _]): Action[Unit, String] = Value[Unit, String](context.field.name)

      val schemaBuilder = new DefaultAstSchemaBuilder[Unit]{
        override def buildObjectType(definition: ast.ObjectTypeDefinition,
                             extensions: List[ast.TypeExtensionDefinition],
                             fields: () ⇒ List[Field[Unit, Any]],
                             interfaces: List[InterfaceType[Unit, Any]],
                             mat: AstSchemaMaterializer[Unit]) = {

          if (definition.name == "Foo"){
            System.out.println(s"${definition.name} has declared interfaces in buildObjectType of: ${definition.interfaces.map(_.name).mkString(",")}")
            System.out.println(s"${definition.name} has a list of interfaces in buildObjectType of: ${interfaces.map(_.name).mkString(",")}")
          }
          super.buildObjectType(definition, extensions, fields, interfaces, mat)
        }

        override def resolveField(typeDefinition: TypeDefinition, definition: FieldDefinition): (Context[Unit, _]) => Action[Unit, _] = {
          typeDefinition match {
            case objTypeDefinition: ObjectTypeDefinition if objTypeDefinition.name == "Foo" =>
              System.out.println(s"${objTypeDefinition.name} has declared interfaces in resolveField ${definition.name} of: ${objTypeDefinition.interfaces.map(_.name).mkString(",")}")
            case _ =>
          }
          resolve
        }
      }

      val schema = AstSchemaMaterializer.buildSchema[Unit](document, schemaBuilder)

      val query =
        """
          |{
          |  foo{
          |     baz
          |  }
          |}
        """.stripMargin
      Executor.execute(schema, QueryParser.parse(query).get)
```

**Comment by OlegIlyenko** [comment]
Thanks a lot for a very details description! I wish more people would include such a nice self-contained and executable snippet that reproduces the issue! It helped me immediately to understand the issue 🏆 

The problem is that you are analyzing the source AST and not the final product. The `typeDefinition` is the original AST that created this type. Unfortunately, at the moment you don't the extension AST in `resolveField`, only the original type definition. You can see the extension AST in [`extendObjectType`](https://github.com/sangria-graphql/sangria/blob/e9a27ceefe60e78d6418f56091953a1af94f1b7f/src/main/scala/sangria/schema/AstSchemaBuilder.scala#L238-L255) when the type is extended, but there you only get already built fields.

Just to make sure the final `ObjectType` is assembled properly, you can output debug message in the resolve function itself. For example, this code:

```scala
def resolve(context: Context[Unit, _]): Action[Unit, String] = {
  println(
    s"actual interfaces of `${context.parentType.name}` " +
    s"are `${context.parentType.interfaces.map(_.name)}` " +
    s"with fields `${context.parentType.uniqueFields.map(_.name)}`")
  Value[Unit, String](context.field.name)
}
```

will output:

```
actual interfaces of `FooQuery` are `List()` with fields `Vector(foo)`
actual interfaces of `Foo` are `List(HasBaz)` with fields `Vector(bar, baz)`
```

So the actual object is assembled correctly and includes all of the extension info. 

How important for your use-case to see the type extension AST in `resolveField`? I think that it is something that can be added (let's say, additional argument: `extensions: List[ast.TypeExtensionDefinition]`), but I wonder whether it is necessary - it would add a breaking change at this point (I think we can still add it, I would consider it pretty minor, but I still would like to understand the actual use-case).

**Comment by Stowe4077** [comment]
We create a list of resolvers with various pattern matching parameters on type, interface name, field name, etc.  We have lots of places in the schema where we want to bind a different resolver to `Foo.baz` over the more generic `HasBaz.baz` (assuming there were other types implementing `HasBaz`) and vice-versa.  So we need to know all the final built info about the parent type and field definition when `resolveField` is called.   That said, we do have a work around that feels less than ideal, but seems to work: we have overridden `buildObjectType` to add in the interfaces into the `ObjectTypeDefinition` since `interfaces` in `buildObjectType` seems to include all the known interfaces whether added via the original type definition or via extensions: ```super.buildObjectType(
        modifiedDefinition,
        extensions,
        () ⇒ mat.buildFields(modifiedDefinition, fields, mat.findExtensions(modifiedDefinition.name)).toList,
        interfaces,
        mat
      )```
