### ISSUE TITLE
Any way to limit a ListInputType argument to max entries?

### ISSUE THREAD

**Issue by meddulla** [sangria-graphql/sangria#268]
Hi,

I've created custom arguments for scalar types like Int and String, where they have to be between some min and max but am a bit stumped on how to do this for Lists because there's no coerce methods available. For example, given this argument

`val idsArg = Argument("ids", OptionInputType(ListInputType(StringType)), ..)
`

how would I go about limiting it only max x entries? Is there any way to do this currently?

If you could point me in the right direction, that would be awesome!

Thanks

**Comment by OlegIlyenko** [comment]
It's an interesting question. There is no way to do this kind of validation on a scalar type. One thing you can do is to perform a validation in the resolve function. But it can become tedious. As a better alternative, I would suggest implementing it as a validation rule. Here is an example of a simple validation rule:

https://github.com/sangria-graphql/sangria/blob/ca21dbe1ebd37e56d2d4e9746936d2b68df7ae16/src/main/scala/sangria/validation/rules/ScalarLeafs.scala

You probably need to handle `sangria.ast.ListValue` and return a validation error if it's size is bigger than the limit. Here are some docs on how to use this new validation rule:

http://sangria-graphql.org/learn/#query-validation

**Comment by meddulla** [comment]
Thank you :) Will look into it.

**Comment by meddulla** [comment]
There are probably better ways to do it but here's an example implementation: https://gist.github.com/meddulla/d28b14d519cb22f677ee18bb2aaf1097

**Comment by romanwozniak** [comment]
Hi,

Sorry for writing into this old topic, but my question is somehow related and after spending a few hours I'm not any closer to finding a solution for it.

So, it's also related to validation of the `ListInputType[_]`. 
I have an argument definition like this:
```scala
val thresholdsArg = Argument("thresholds", ListInputType(FloatType))
```
What I need is to validate an exact size of the input list (i.e. list.length **should be**  <some number>) and to make sure, that the elements in this list are in order.

I guess, the first part could be solved in a similar way that @meddulla solved it before, however, it will work only in a case, when that argument is passed directly into the operation, but it will not work, in case when the argument is defined as variable and passed to operation via variable name.
This will work:
```
{
  alerCounts(thresholds: [0.1, 0.5, 1.0]) {
    count
  }
}
```
However this whouldn't:
```
query($thresholds: [Float!]!) {
  alerCounts(thresholds:$thresholds) {
    count
  }
}
variables {
  "thresholds": [0.1, 0.5, 1.0]
}
```

The second part is even trickier, because for validating the sort order of the input `ListInputType[FloatType]` I need to resolve variable values and I'm not sure if it's even possible inside `ValidationRule`

Appreciate some help on the topic, because there are not so many information about validation in sangria.

**Comment by bc-dima-pasieka** [comment]
@romanwozniak did you find a way to resolve it by any chance? 😃

**Comment by bc-dima-pasieka** [comment]
👋 Quick update on how we resolved the case when the argument is passed as a variable (there are actually two cases to take into account)

**1. Case when the variable is sent as a part of `variables`:**

```graphql
query getProducts($pageSize: Int) {
  products(first: $pageSize) {...}
}
{"pageSize": 10}
```

We create query validators (including our custom rule) dynamically with current variables injected and then just check the value by name:
```scala
case class CustomArgRule(variables: Json) extends ValidationRule {
  private val variablesMap: Map[String, Json] = ??? // convert json object to map so it's easier to use

  override def visitor(ctx: ValidationContext): AstValidatingVisitor = new AstValidatingVisitor {
    override val onEnter: ValidationVisit = {
      ...
      // when iterating through `Field` arguments you have access to variable name -
      // check if your variable exists in variables map
      case VariableValue(name, _, _) => variablesMap.get(name)
    }
  }
}
```

**2. Case when the variable is NOT sent as a part of `variables` but has the default value:**
```graphql
query getProducts($pageSize: Int = 10) {
  products(first: $pageSize) {...}
}
```

```scala
case class CustomArgRule extends ValidationRule {

  override def visitor(ctx: ValidationContext): AstValidatingVisitor = new AstValidatingVisitor {
    override val onEnter: ValidationVisit = {
      ...
      // when iterating through `Field` arguments you have access to variable name -
      // find `OperationDefinition` among ancestors (it has default variable values)
      // and check if your variable exists there
      case VariableValue(name, _, _) => extractVariableDefaultValue(name, ctx.typeInfo)
    }
  }

  private def extractVariableDefaultValue(
    variableName: String,
    typeInfo: TypeInfo
  ): Option[Value] =
    typeInfo
      .ancestors
      .collectFirst { case operation: OperationDefinition =>
        operation.variables.find(_.name == variableName).flatMap(_.defaultValue)
      }
      .flatten
}
```
