### ISSUE TITLE
Fetcher for non-ID arguments

### ISSUE THREAD

**Issue by tgvashworth** [sangria-graphql/sangria#280]
I'd like to be able to use a `Fetcher` to make batch calls with a list of non-ID inputs.

For example, looking up Twitter users by screen name. Screen names are not IDs, and are returned case-sensitively. The input `screen_name` argument could be `twitter` but the returned value might be `Twitter`.

Using a fetcher with `HasId` therefore doesn't work because the input and output can't be matched up.

It seems like an extension to the Fetcher interface that would allow mapping the `Id` in the `Deferred` instance to a normalized value would work, as I can use the same normalizing function in the `HasId` implementation.

Does this make sense? There might be another way.

Also: I think this is something I could work on, if you can give some direction as to the best approach.

**Comment by OlegIlyenko** [comment]
I think something like this is already possible to achieve. 

If we model problem a little bit differently, we can represent a `screenName`-based lookup as a form of 1:1 relation. So `Tweet` still has strict identity and `id`-based fetcher, but in addition to it we can also implement a screen name relation. In fact, relation fetchers have special support for this kind of mapping to an original relation ID (which is a `screenName` in this case).

Let me demonstrate it on a small example. First, lets define some model and repository that mocks actual fetching and fuzzy matching:

```scala
case class Tweet(id: String, screenName: String)

object Tweet {
  implicit val hasId = HasId[Tweet, String](_.id)
  implicit val graphqlType = deriveObjectType[Unit, Tweet]()
}

class Repo {
  val tweets = List(
    Tweet("one", "Foo"),
    Tweet("two", "BaR"))

  def loadByIds(ids: Seq[String]) =
    Future.successful(tweets.filter(t ⇒ ids.contains(t.id)))

  def loadByScreenName(screenNames: Seq[String]): Future[Seq[(String, Tweet)]] =
    Future.successful(
      screenNames.flatMap(original ⇒
        findByFuzzyScreenName(original).map(original → _)))

  private def findByFuzzyScreenName(fuzzyScreenName: String) =
    tweets.find(_.screenName.toLowerCase == fuzzyScreenName.toLowerCase)
}
```

Now comes the fetcher:

```scala
val ScreenNameRel = Relation[Tweet, (String, Tweet), String](
  "byScreenName", {case (originalScreenName, _) ⇒ Seq(originalScreenName)}, _._2)

val tweets = Fetcher.relCaching(
  (repo: Repo, ids: Seq[String]) ⇒ repo.loadByIds(ids),
  (repo: Repo, rels: RelationIds[Tweet]) ⇒ repo.loadByScreenName(rels(ScreenNameRel)))
```

This variation of relation supports an intermediate type ` (String, Tweet)` which represents a connection between non-normalized original screen name and the tweet.

And the actual schema:

```scala
val QueryType = ObjectType("Query", fields[Repo, Unit](
  Field("tweet", OptionType(Tweet.graphqlType),
    arguments = IdArg :: ScreenNameArg :: Nil,
    resolve = _.withArgs(IdArg, ScreenNameArg)((id, screenName) ⇒
      id.map(tweets.deferOpt)
        .orElse(screenName.map(tweets.deferRelOpt(ScreenNameRel, _)))
        .map(Action(_))
        .getOrElse(Value(None))))))

val schema = Schema(QueryType)
```

`tweet` field loads the tweet either by an `id` or non-normalized `screenName`. After you execute this query:

```scala
val query =
  gql"""
    {
      t1: tweet(id: "one") {id screenName}
      t2: tweet(screenName: "FOO") {id screenName}
      t3: tweet(screenName: "bar") {id screenName}
    }
  """

Executor.execute(schema, query, new Repo, deferredResolver = DeferredResolver.fetchers(tweets))
```
you will get this JSON:

```json
{
  "data": {
    "t1": {
      "id": "one",
      "screenName": "Foo"
    },
    "t2": {
      "id": "one",
      "screenName": "Foo"
    },
    "t3": {
      "id": "two",
      "screenName": "BaR"
    }
  }
}
```

Nice thing about this approach is that returned tweets would be put in the ID-based cache and in relation cache. Also it is more extensible since you can also define other tweet lookup criterias with new relation types.

What do you think about it? Do you think that this approach can be suitable in your scenario?

**Comment by tgvashworth** [comment]
This was *super* helpful, thank you. I tried out an implementation today that worked really well.
