### ISSUE TITLE
Calling deriveObjectType in companion object for a trait mixed into multiple classes

### ISSUE THREAD

**Issue by dsilvasc** [sangria-graphql/sangria#298]
Hi,

Should it be possible to define a trait whose companion object provides implicit sangria object types?  I'd like to do that to not have to define companion objects and implicits for each type in my schema, as below:

```scala
// Derivable.scala
trait Derivable

object Derivable {
  implicit def graphqlType[T <: Derivable: ClassTag]: ObjectType[Ctx, T] =
    deriveObjectType[Ctx, T]()
}

// Picture.scala
case class Picture(width: Int, height: Int, url: Option[String]) extends Derivable

// Product.scala
case class Product(id: String, picture: Picture) extends Derivable
```

Right now it fails to compile with:

```
Derivable.scala:13: Field list is empty
    deriveObjectType[Ctx, T]()
                            ^
```

**Comment by OlegIlyenko** [comment]
Yes, it is possible to derive a type inside of a companion object. In this case though, you probably want to derive `Picture` and `Product` independently. Unfortunately, it will not work with `Derivable` trait.

**Comment by ayyappanramamuniappa** [comment]
@OlegIlyenko I am trying to deriveObjectType for complex object type with nested classes. Is it not possible to derive the whole object?

**Comment by OlegIlyenko** [comment]
No unfortunately `Picture` and `Product` types need to be derived separately. Since `deriveObjectType` is a macro, it needs to know a specific derived type (so it can't be a type parameter). In on of the projects I'm working on, we had something similar, so we cated a custom macro to discover and derive the whole hierarchy of input object types. But that custom macro is application/domain specific so it makes some assumptions about the type hierarchy and how it's used.
