### ISSUE TITLE
Inconsistent EnumValue coercion

### ISSUE THREAD

**Issue by Axxiss** [sangria-graphql/sangria#300]
As part of moving our schema to a full(ish) IDL version.

 We're facing some issue with enum coercion. We defined a `@enum` directive to be able to override the value a of an enum using the IDL, that part is working nicely. Nevertheless, when coercing the enum from an input object we can't get the custom value.

As result of applying the directive we are overriding `enumValue` from `DefaultAstSchemaBuilder`

``` scala
  override def enumValue(definition: EnumValueDefinition): String = {
    definition.directives.collectFirst { case EnumDirective(d) => d.value }.getOrElse(super.enumValue(definition))
  }
```

This is the schema we're using to test it.

``` graphql
enum SomeEnum {
  FOO @enum(value: "foo_value")
  BAR @enum(value: "bar_value")
}

input SomeInput {
  inputEnum: SomeEnum
}
```

Let's say we use `FOO` in two different mutations with different input args, this are the scenarios we are testing:

### Scenario 1

The enum is a direct argument of the mutation.

``` graphql
extend type Mutation {
  aMutation(inputEnum: SomeEnum): SuchPayload
}
```

In this case, doing `ctx.arg("input")` will return `foo_value`

### Scenario 2

The enum is a child of a complex type. This is the real use case, what we'll be using.

``` graphql
extend type Mutation {
  anotherMutation(input: SomeInput): SuchPayload
}
```

In this case, doing `ctx.arg("input")` will return the following json

``` json
{ "inputEnum": "FOO" }
```

which is misleading, as in one case the enum value is coerced and in the other one it doesn't.

### Current status

We tried to track down the issue through sangria codebase, and we reach to this point

https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/execution/ValueCoercionHelper.scala#L329-L334

where `case raw` returns `foo_value` and `case standard` returns `FOO`. Eventually, I was tempted to modify`coerceOutput` (which I did) and some test (59 😅 ) failed. AFAIK, `coerceOutput` will make sure that the right value is returned to the client, so probably that change didn't make any sense.

Is there anything we missing? If you think this is a bug, if you could provide any hint to where to look, we will more than happy to provide a patch.

cc:/ @BjRo

**Comment by OlegIlyenko** [comment]
Thanks for the very detailed description! I look into it later today

**Comment by OlegIlyenko** [comment]
I tried to reproduce the scenario, that you have described, as close as I can. The test is green and it works as expected:

https://github.com/sangria-graphql/sangria/blob/23a7e2290fe1e8bd1615cc1e66ed02af055f5391/src/test/scala/sangria/schema/ResolverBasedAstSchemaBuilderSpec.scala#L300-L368

(the `SimpleEnumValueResolver` is used by `enumValue` so it goes through the same mechanism)

Maybe you can verify that in your case resulting `SomeEnum` type contains all expected data, just as a first debugging step? I mean something simple like this:

```scala
val enum = schema.allTypes("Color").asInstanceOf[EnumType[_]]

enum.values.map { v ⇒
  println(v.name + " = " + v.value)
}
```

in my case it prints:

```
RED = #FF0000
GREEN = #00FF00
BLUE = #0000FF
```

If it produces expected results, then maybe you can make a small repro example, if possible? (similar to the one I linked)

**Comment by Axxiss** [comment]
Thanks a lot @OlegIlyenko for taking a look so quickly. 😄 

Yes, types are there and contains the right information. This is the output:

```
[info] FOO = foo_value
[info] BAR = bar_value
```

We'll try to come up with a test case for this.

**Comment by OlegIlyenko** [comment]
Thanks again for a test, it helped a lot to understand the nature of the problem!

Turns out that it is a bit more involving. After short investigation I realized that it is not a bug, but rather an intended behaviour. Though it was not immediately apparent based on the test scenario. Whether this behaviour is suitable in this case or might be improved, is a different question :)

Let me first explain why it is happening. Since you are using `JsObject` to represent an input type, the standard type-class based mechanism takes over (based on the `FronInput` type-class). The execution engine does all necessary validation, but then delegates internal object representation construction to the `FronInput` type-class.

Enum value coercion is a but different from scalar values. It represents a conversion of external enum value representation into the internal one. Internal representation might be an object of an arbitrary type, like `scala.Enumeration`, `Int` or even something completely unrelated like `java.util.Date`. Since you are using `JsObject` as the target, there is no way to represent an arbitrary type as a JSON. because of this `coerceOutput` is used to get a value that is guaranteed to be representable as a JSON value (so it's not like coercion does not take place: in addition to coercing the input value it also coerces it to the output representation). So from this perspective, `coerceInput`/`coerceOutput` are not intended as value transformation tool, but rather as mechanism for converting between value type representations (internal/scala types and external/string). In your scenario internal and external representations are of the same type `String` but represented with different values, but from the perspective of the library they are exact equivalents and interchanged when used for different purposes. Since in general internal representation can't be represented by `JsValue`, the library decides for an equivalent external representation.

The `RawResultMarshaller`, that you have seen before, is a bit special. It gives a promise to an execution engine that it is able to handle values of arbitrary type, even values that only represented on JVM (like `scala.Enumeration` or `java.util.Date`). This what allows it to hold internal enum value representation instead of the external one. `RawResultMarshaller` is normally creates `Map[String, Any]` (or in other words `InputObjectType.DefaultInput`). The direct scalar and enum argument values are always unmarshalled with `RawResultMarshaller`. This is why you see an internal value representation when it is used as an argument, but an external value representation when used inside of an input object which is represented with `JsObject`. This also explains why my test was successful: I used the default which deserializes input objects in `InputObjectType.DefaultInput`, thus contains internal scalar and enum value representations.

I hope this clarifies the witnessed behaviour. Would love to hear your opinion on described mechanisms. 

To mitigate this issue, I think a good approach would be to put the value transformation and adjustment logic in the resolve functions instead of the enum or scalar values. Alternatively you can use different `ResultMarshaller` and `FromInput` instance to allow internal value representation (though in this case it will affect all enum and scalar values).

**Comment by Axxiss** [comment]
Yes, we where thinking something like that as using `coerceOutput` during input marshalling felt quite odd. Furthermore, passing `isArgument` as `false` caught our attention.

https://github.com/sangria-graphql/sangria/blob/33d908c02b6047260c7a4c55b1ec236238604aae/src/main/scala/sangria/execution/ValueCoercionHelper.scala#L261

Triggering the discussion if, an argument children should be treated as arguments or not. We went ahead and as part if a trail and error approach we forwarded `isArgument` instead of passing `false`. That allowed us measure the impact of replacing

https://github.com/sangria-graphql/sangria/blob/33d908c02b6047260c7a4c55b1ec236238604aae/src/main/scala/sangria/execution/ValueCoercionHelper.scala#L331

with

``` scala
                val theValue: String = if (isArgument)
                  v.toString
                else
                  enum.coerceInput(v)
                Resolver.marshalEnumValue(theValue, standard, enum.name)
```

When running the test suite we got the following

```
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error] 	sangria.execution.ScalarMiddlewareSpec
[error] 	sangria.marshalling.EnumInputTypeSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

Where `EnumInputTypeSpec` does the right conversion but it fails due to the error I mention on the PR. So this works for our use case and seems that doesn't have a big impact on the current test suite nevertheless I'm not sure of the possible side effects. 

Do think is possible to introduce something like that or the implications of doing it are to expensive/complicated/whatsoever?

If a fix like that doesn't make sense, then we'll have to do the transformation as part of the resolution

**Comment by OlegIlyenko** [comment]
> Do think is possible to introduce something like that or the implications of doing it are to expensive/complicated/whatsoever?

In general, I do think that it should be possible to provide a solution for this particular use-case. That said, if we introduce a solution that is part of the `EnumType`, then I would like to make sure that it conceptually fits well in the overarching marshaling framework. Relying on `isArgument` flag does not feel right at the moment since conceptually it has nothing to do with the fact whether the value should or should not be coerced. Even if it works in particular setup, most probably it will produce unexpected results in a slightly different setup.

As I was investigating the issue, I was thinking about introducing a new coercion function dedicated to internal enum-value transformation. This would fulfill the use-case nut also will introduce a new concept and complexity. I'm still not 100% sure whether it is worh the introduction, especially if more flexible and robust mechanism is available already, like value transformation in resolve functions. You still should be able to access all relevant enum directive information from there and isolate and centralize the transformation logic.

So I'm pretty open to working on an alternative solution for this use-case, but would prefer to avoid introducing new concepts until we have a solid argument in favor of these changes.

**Comment by Axxiss** [comment]
For our current setup, doing the enum coercion on the resolver is not possible, as the resolvers for SDL defined types are built dynamically. Hence we can't do `MyEnumType.coerceUserInput` because at resolution time we already lost the type reference. So that option was discarded.

The second option we had in mind was to infer enum types values manually, we got a draft version working but we didn't feel happy about the solution as it will add an extra weight in the performance of our product.

Finally, we started to move towards replacing the marshaller with `CoercedScalaResultMarshaller` this gave us the converted values but it is affecting other parts of our expression system.

Long story short, expressions are this snippets that looks like string interpolation `#{something}`

``` graphql
enum TestEnum {
  foo @enum(value: "FOO_VALUE")
  bar @enum(value: "BAR_VALUE")
}

input TestInput {
 theEnum: TestEnum
}

input DebugResolver @httpGet(url: "/debug/it/enum/#{enum}/input/#{input}") {
  input: Expression
  enum: Expression
}

extend type Query {
  testIt(enum: TestEnum, input: TestInput): String @debugResolver(enum: "#{ctx.args.enum}", input: "#{ctx.args.input.theEnum}")
}
```
So, when doing `#{ctx.args.input.theEnum}` input was represented as a json and `theEnum` was extracted from `input`. This our use case for extracting `InputObjectTypes` as json.

Hope this shed some light into our use case.

cc @certainty

**Comment by Axxiss** [comment]
Furthermore, based on what you said before

> Since you are using JsObject as the target, there is no way to represent an arbitrary type as a JSON. because of this coerceOutput is used to get a value that is guaranteed to be representable as a JSON value

Then shouldn't be possible to allow Sagria's users to provide an implementation that guarantees an object conversion to JSON and keeping the current behaviour as the default?

**Comment by OlegIlyenko** [comment]
Yes, I also wanted you point out similar idea.  Since you operation purely with JSON values, even for internal representations, then I think you can try to mix one of the JSON-based `ResultMarshaller`s with `RawResultMarshaller`. This will allow you to serialize `InputObjectType` to a JSON value and preserve internal enum value representations. Have you already tried it?

**Comment by Axxiss** [comment]
Thanks for the hint Oleg! 

Extending `RawResultMarshaller` and doing the conversion to Json there seems to be working. Thanks again for the detailed answers and the support provided :)
