### ISSUE TITLE
Sangria 1.3.3 changelog doesn't mention two potential regressions

### ISSUE THREAD

**Issue by BjRo** [sangria-graphql/sangria#308]
Hi @OlegIlyenko,

we've tried to upgrade to Sangria 1.3.3 and ran into two regressions. All in all they're not big and manageable on our side. 

I'm putting them down here, so that this doesn't get lost (and also to use the opportunity to get some input on those points from you). I hope that's fine for you!

## Executable Definitions
The first one is that there's a [new query validation rule](https://github.com/sangria-graphql/sangria/commit/b453be54c657429c073a1c25ffd83506229a3b4b), that doesn't seem to be mentioned in the `Changelog`. 

This broke most of our IDL based schema tests, since we're using `QueryValidator.allRules` to validate incoming schemas. Filtering out the `ExecutableDefinitions` rule, fixed those tests. 

In general what do you think would be a good approach to re-use rules for validating incoming schemas? My feeling is that were probably a bit too eager to re-use the existing validation rules for our IDL there and should be more selective in the future. Thoughts?

## Mandatory fields in input types
This one is a bit unfortunate for us. We basically re-use `input` types for declaratively defining resolvers (in lack of an actual construct that can be parameterised for defining directives).

```graphql
input IdlResolver1 @httpGet(url: "/profiles/profile/2") {}
```
After upgrading we saw several of the following errors:

```
[error]    sangria.parser.SyntaxError: Syntax error while parsing GraphQL query. Invalid input ""/test") {\n}", expected ValueConst, ArgumentConst, DirectiveConst or InputValueDefinition (line 7, column 32):
[error]    input MyResolver @httpGet(url: "/test") {
[error]                                   ^ (QueryParser.scala:433)
```

After staring at this a bit, we tracked the change in behaviour down to [this commit](https://github.com/sangria-graphql/sangria/commit/b8af9168b6252457f69e53c6c43560d24204099f#diff-9c1db5cb2ae322dd07ca363370f6c46cR239), where the `input` type definition was changed to have at minimum one field.

From 

```scala
 ~ InputValueDefinition.*
```
to 
```scala
~ InputValueDefinition.+
```

From a pure spec perspective I understand the change (input types without fields don't make a lot of sense). And I guess most of our time our resolvers will have fields (we use this for parametrizing the resolver)

```graphql
input UpdateSettingsResolver @httpPatch(
   url: "/rest/#{product}/settings/#{ctx.rid}", 
   body: "#{settings}") {
    product: Expression!
    settings: Expression!
}
```

It took us a bit time to track it down. I really wonder whether it's possible not to rely on `input` types on our side for this, but we're unsure how else to achieve the same level of re-usablility and parametrisation. Maybe a `directive` keyword. Or means to provide extensions to IDL. Do you have ideas in this regard?

Thx for your input in advance!

**Comment by OlegIlyenko** [comment]
Thanks a lot for such a fast and thorough feedback! I should have mentioned both changes in the release notes since they were potentially breaking changes.

> Executable Definitions

Indeed filtering this rule is currently the way to go:

```scala
val validator = 
  QueryValidator.ruleBased(QueryValidator.allRules.filterNot(_.isInstanceOf[ExecutableDefinitions]))
```

In general, I think re-using a `QuertValidatior` is a good approach to also validate the SDL. It provides quite flexible and robust mechanism. The validation rules might slightly differ, but otherwise, I think it is the right tool. I use it in `ResolverBasedAstSchemaBuilder`.

> Mandatory fields in input types

Good point, I haven't thought about it from this perspective. Just to reference the relevant part of the spec:

https://github.com/facebook/graphql/pull/90/files#diff-c9d195396161bb690c5fd8899af11d78R238

It's hard for me to assess this particular use-case, but in general, I think in some scenarios it might make sense to skip the field list since fields might be generated in one way or another (e.g. with directives). 

One idea I had is to implement mandatory-field-list requirement as a validation rule rather than baking it into the parser. This can be a much flexible solution where it effectively produces the same results but allows for more complex directive-based workflow. I will follow up this point an propose this in the spec PR.

**Comment by BjRo** [comment]
I managed to get our test code base running on `1.3.3` by turning

```graphql
input IdlResolver1 @httpGet(url: "/profiles/profile/2") {}
```
into

```graphql
input IdlResolver1 @httpGet(url: "/profiles/profile/#{id}") {
   id: Expression = "2"
}
```

In general moving the fields rule from the parser to the validation rules seems like a good solution to me. It definitely would make live for us easier (since we're using the resolver definitions to actually generate directives) and would also allow for customizations.

Let's see what FB thinks about that. Thank you for bringing that to their attention and in general for your fast response @OlegIlyenko!!!

**Comment by OlegIlyenko** [comment]
I will close this issue since we discussed the changes and appropriate updated were introduced in the spec and reference implementation. These new additions would be implemented and released in the next sangria version.
