### ISSUE TITLE
DeriveObjectSetting for methods' arguments description

### ISSUE THREAD

**Issue by fehu** [sangria-graphql/sangria#318]
`@GraphQLDescription` is not a universal solution to argument description problem because
1. one might not have access to the method's code,
2. annotation usage would create a dependency on _sangria_.

As you've explained in question #232, 
> it would be relatively hard to precisely identify exact argument you want to document

But it is still [solvable](https://github.com/fehu/sangria/commit/f6b32a41311b61f5ebf437d3fb8ac82416ba8129) except for overloaded methods.

Since, as I understand, such methods cannot be renamed using derivation settings, and the only way to avoid `java.lang.IllegalArgumentException: All fields within a Type should have unique names!` is to use `@GraphQLName` annotation - one is forced to either use the annotations or create a `schema.Field` manually.

For the not-overloaded methods, the arguments are uniquely identified by method's and argument's names and could be configured using derivation settings.

**Comment by OlegIlyenko** [comment]
In general, I don't have anything against introducing support for arguments. AFAIR, I haven't added them in the first place because I thought that it would be a bit cumbersome to use them and I assumed that if one exposes methods with arguments, then these methods are specifically designed for GraphQL API. So one has full control over them. These assumptions might be wrong, of course.

If there is a compelling reason to support arguments via settings (and not only via annotations), then let's do it. Would you be interested in preparing a PR? 

The issue with method overloading is a general problem and, AFAIU, not related to argument documentation. I guess the current solution for resolving it would be an annotation-based approach.

**Comment by fehu** [comment]
Yes, I can prepare a PR. I've added settings for specifying arguments' descriptions and default values; I'm just not sure that the names I chose are consistent with yours.

| Setting name | Description |
|------------------|----------------|
| `MethodArgumentDescription` | set description for a single argument |
| `MethodArgumentsDescription` | set descriptions for multiple arguments |
| `MethodArgumentDefault` | set default value for a single argument |
| `MethodArgument` | set description and default value for a single argument |

Would you like that I add more settings, like for renaming the arguments?

**Comment by OlegIlyenko** [comment]
Looks great 👍 A setting for renaming an argument also sounds like a good idea.
