### ISSUE TITLE
Expressing partial results in the fetcher

### ISSUE THREAD

**Issue by folone** [sangria-graphql/sangria#323]
Hi 👋

I've been working on supporting lists of results (in `data` part of the response), with a list of failures that occurred during the execution (in`errors` part of the response). So far, what I ended up with is having fetcher relations parameterised by a `Try[A]`:

```scala
val myFetcher = Fetcher.rel(
    (ctx: QueryContext, ids: Seq[String]) => {
      val things: Future[Try[Thing]] = ctx.getThingsById(ids)
      things
    },
    (ctx: QueryContext, rels: RelationIds[Try[Thing]]) => {
      val rel = rels(ThingRel)
      val things: Future[Try[(String, Thing)]] = ctx.getThingsByRel(rel)
      things
    },
    config = FetcherConfig.maxBatchSize(100).caching(FetcherCache.simple)
  )(HasId(_.map(_.id).getOrElse("non-existing")))

val ThingRel = Relation[Try[Thing], Try[(String, Thing)], String](
    "byThing",
    {
      case Success((thing, _)) => Seq(thing)
      case _ => Seq.empty
    },
    _.map(_._2)
  )
```

And then turning them into partially successful values in the schema definition:

```scala
Field(
  "thing",
  OptionType(ThingType),
  Some("Fetch a Thing by some relation"),
  arguments = RelationArgumentType :: Nil,
  resolve = ctx => propagatePartialErrors(ctx.ctx.fetchers.myFetcher
    .deferRel(ThingRel, ctx.arg(RelationArgumentType)))
)

def propagatePartialErrors[A, Ctx](deferred: Deferred[Try[A]]): DeferredValue[Ctx, Option[A]] =
    DeferredValue(deferred).mapWithErrors {
      case Failure(failure) => None -> Vector(failure)
      case Success(result) => Some(result) -> Vector.empty
    }
```

This seems to be working fine, but there are several concerns that I've had with this approach. Firstly, we seem to be treating `Try[A]` as a successful value in the fetcher. Which causes odd things like `HasId(_.map(_.id).getOrElse("non-existing"))`. And secondly, wrapping everything in `propagatePartialErrors(...)`.

I was wondering if there's a better way to do this. And also, if it would be considered a useful addition to the project to have something like `.deferTry`, to somehow hide all that logic.

WDYT?

**Comment by OlegIlyenko** [comment]
Thanks for sharing these concerns, George!

I think it is important to point out these two assumptions that were made in the design of Fetch API:

* Every fetch operation is happening in batch, so either the whole batch fails or the batch loading is successful
* In case of successful batch results, there is a way to associate the result and an ID that was used to load it

This is why, at the moment at least, it does not provide more fine-granular error reporting. That said, the underlying low-level abstraction (`DeferredResolver`) does provide more fine-granular error reporting (error for every individual deferred value might be reported as failed).

Since you lift an error in the actual the result value via `Try`, I assume that you do additional processing after the batch was loaded (which might fail as well). Is it correct? In this case, I think `Try` is not very suitable data structure since it does not correlate an error to the entity ID (or corresponding relation ID). Something like this might be a better abstraction for this (or even just a simple tuple `(Id, Try[Result])`):

```scala
sealed trait FetchResult[Id, T] {
  def id: Id
}

case class SuccessfulFetch[Id, T](id: Id, value: T) extends FetchResult[Id, T]
case class FailedFetch[Id, T](id: Id, error: Throwable) extends FetchResult[Id, T]
```

I assume that in your situation it is possible  (or maybe even desired) to maintain the relationship between an error and corresponding entity ID. This will avoid necessity for things like `HasId(_.map(_.id).getOrElse("non-existing"))`. I guess you would also need to customize the `FetcherCache` a bit and ignore all failed results.

Regarding `.deferTry`. I'm not 100% sure it will provide much of a help in this case. `Try` does not have a capability to associate an error with entity ID. This means that even if the error is lifted in a resulting value, failed value result will never be able to reach the field that asked for this value in the first place (since all failed results get an ID `"non-existing"` which none of the fields requested). The same is true for relation IDs.

Generally, I would be happy to enhance the Fetch API, but I'm not yet sure how more fine-granular error propagation might be introduced without a moderate increase in complexity of the whole thing. That said, If the mechanisms that you are trying to implement is mechanically quite different from what high-level Fetch API provides, then you might also consider implementing it with low-level API (with a custom `DeferredResolver`). It is not a mutually exclusive choice either - you can use Fetch API for some parts of the application with a fallback on a custom deferred resolver. You might also consider building a small generic high-level API on top of the `DeferredResolver` that is optimized for a set of application-specific use-cases (this is actually how Fetch API is implemented with [`FetcherBasedDeferredResolver`](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala))

Would be to hear your thoughts on this :)

**Comment by folone** [comment]
Thanks for the pointers @OlegIlyenko! This is very helpful: I've indeed ended up with having an `(Id, Try[Thing])` construct at the end, but I like your suggestion much more. Will re-work to have something similar. Also thanks for mentioning the `FetcherCache`: didn't think about that.

I'll close this issue for now. Will let you know if I end up with anything reusable.

**Comment by tgvashworth** [comment]
Great answer, thanks @OlegIlyenko. One thing I want to follow up on...

> Every fetch operation is happening in batch, so either the whole batch fails or the batch loading is successful

In our case this doesn't work so well, and I think it might be worth considering adding support for partial batch success to the fetcher.

For example, we batch up requests to fetch users. Whether or not that user is available to the original requester is a result of a complex set of visibility and safety rules, and so only some of the users might actually be available.

We would like to be able to return the "best-possible" result to the GraphQL API client, so we will opt for partial success where we can, *and* let the caller know what went wrong.

```graphql
query {
  ok: user_by_screen_name(screen_name: "ok") {
    screen_name
  }
  suspended: user_by_screen_name(screen_name: "suspended") {
    screen_name
  }
}
```
```json
{
  "data": {
    "ok": {
      "screen_name": "ok"
    }
  },
  "errors": [
    {
       "path": ["suspended"],
       "code": 63,
       "message": "User is suspended."
    }
  ]
}
```

For now I think we're OK to move forward with your suggestion, but the fetcher interface is great and I think it would be helpful to have it support this kind of partial success in a batch call!

What do you think?

---

As an aside, it makes me think again that we should model most key object types as Unions of their type — eg. `User` and an `Error`. That way errors are built into the schema themselves, and we don't have this problem... 🤔

**Comment by OlegIlyenko** [comment]
Thanks for the detailed feedback, Tom! I think you described a valid use-case. I will think on how partial error propagation might be incorporated in Fetch API, maybe we can find a good way to introduce it. I would also appreciate your ideas on this matter.

Explicitly modeling errors might have some advantages. It's often used to represent user-facing form validation errors, for instance. Based on your description, it feels like this error state is a part of the business domain, so i think it would be appropriate to represent it in the GraphQL type system. As far as i'm aware,`"errors"` array in the response is primarily designed for technical errors like, for instance, type system errors, connection errors, unexpected exceptions, etc.
