### ISSUE TITLE
`grapql` string context macro to create parsed document and verify query at compile time

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#33]

**Comment by dlreeves** [comment]
Not sure where this lands on your priorities, but I have been messing with this over the last couple days. It's been a while since I've done any Scala code, but I was able to get something that is able to parse a graphql document that is a literal string at compile time.

If you are taking pull request I'll try to clean it up and send one your way

**Comment by OlegIlyenko** [comment]
Of course, I would appreciate this!  Even if it's not perfect yet, we can improve over the time, but we already will have something functional to begin with.
