### ISSUE TITLE
RenameInputField fails for mutation

### ISSUE THREAD

**Issue by nielspedersen** [sangria-graphql/sangria#330]
Mutation arguments based on derived input object types and having an input field renamed will fail on both names (original and renamed):

```scala
val TestInputObject = deriveInputObjectType[TestClass](
    RenameInputField("name", "newName"))

  val TestArg = Argument("testArg", TestInputObject)

  val Mutation = ObjectType(
    "Mutation", fields[Data, Unit](
      Field("mutate", StringType,
        arguments = TestArg :: Nil,
        resolve = c ⇒ c.ctx.testFunction(c.arg(TestArg))
      )))
```

Using the above example results in this response:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Argument 'testArg' has invalid value: Object is missing required member 'name' (line 2, column 19):\n  mutate(testArg: {\n                  ^",
      "path": [
        "mutate"
      ],
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ]
    }
  ]
}
```

Trying to use the original name again:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Argument 'testArg' expected type 'TestClass!' but got: {name: \"nanananananana batman!\"}. Reason: 'name' Field 'name' is not defined in the input type 'TestClass'. (line 2, column 19):\n  mutate(testArg: {\n                  ^\n (line 3, column 5):\n    name: \"nanananananana batman!\"\n    ^",
      "locations": [
        {
          "line": 2,
          "column": 19
        },
        {
          "line": 3,
          "column": 5
        }
      ]
    },
    {
      "message": "Argument 'testArg' expected type 'TestClass!' but got: {name: \"nanananananana batman!\"}. Reason: 'newName' Not-null field 'newName' of type 'String!' defined in the 'TestClass' input type is missing. (line 2, column 19):\n  mutate(testArg: {\n                  ^",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ]
    }
  ]
}
```

Full example in this gist:
https://gist.github.com/nielspedersen/44784526fd8a621657e1687c55e582f6

**Comment by OlegIlyenko** [comment]
Thanks a lot for providing a great example snippet that demonstrates the issue! 👍 

The error actually comes from spray-json: you renamed field in GraphQL schema, but the spray-json's `JsonFormat` does not know about it and still expects property with the old name to be present. You probably need to also update the JSON format here:

```scala
implicit val implicitititit = DefaultJsonProtocol.jsonFormat1(TestClass)
```

**Comment by nielspedersen** [comment]
Thanks for a very quick reply!

I see, I think I understand now. I have changed the implicit format to the following:

```scala
implicit val implicitititit = DefaultJsonProtocol.jsonFormat(TestClass, "newName")
```

And that works completely as expected! Thank you very much for the help :)

**Comment by acjay** [comment]
Ah, interesting. So not sure if I understand the data flow here, but it seems like the input is checked against the schema, mapped into JSON (since the input type syntax isn't really JSON), and then converted into the destination object using the project's configured JSON library? Should it maybe be the case that `RenameInputObject` causes the text field to be renamed before attempting deserialization? Just wondering, because in my case, we use an automatically derived `JsonFormat` for other purposes, so changing the format isn't a workable solution. Or maybe it should be possible to provide a mapping from input to JSON serialization separately, since it seems like this problem would probably still happen even without using the macro.

**Comment by OlegIlyenko** [comment]
@acjay yes, I think you got it right. The second step ("and then converted into the destination object using the project's configured JSON library") is based on the type-class based deserialization (like `JsonFormat`) so it should be possible to define several instances of these for the same scale type: one instance is the default that is used in other parts of the application and the second one is only used withing GraphQL schema.

As an alternative, you can still rely on the set of standard deserializers, but make a series of JSON transformations for values that are coming from GraphQL. In this case, you would need to implement new `FromInput` instances where the transformation would take place. This is what we also did in our project since we have the same issue. There are small differences in representation, like localized value which is represented as `{"en": "Some Name"}` in our REST API and as `[{"locale": "en", "value": "Some Name"}]` in the GraphQL API. We are still useing the same JSON deserializers for both API, but do some minor transformation for new GraphQL API inputs (in `FromInput`).
