### ISSUE TITLE
Performance - High CPU Usage

### ISSUE THREAD

**Issue by alyssaBiasi** [sangria-graphql/sangria#331]
While running performance tests, we have noticed that CPU usage is quite high (sitting between 70-85%). As you can see from the performance test results below, response times are looking good, however, we are concerned about how far out we will need to scale to handle peak production load.

| Parameter           | Value      |
|---------------------|------------|
| Test duration   | 10 minutes |
| Ramp up time         | 10 minutes |
| Number of flood grid nodes   | 3          |
| Number of threads   | 400        |
| Instance size       | c4.large   |
| Number of instances | 15         |

![performanceresults](https://user-images.githubusercontent.com/2237917/35363475-4077ef9a-01be-11e8-93cf-11a298521357.png)

### Steps taken

- Fragmented request with overlapping fields (as per the [example posted in gitter](https://gitter.im/sangria-graphql/sangria?at=5a600f6f290a1f4561a1055a))
- Flattened request with no fragments or overlapping fields
  - Slight improvement but CPU was still 60-80% for the entire test
- Cached the results of `QueryParser.parse`
  - No change
- Added slow log
  - No queries logged with a threshold of 10s

It's also worth noting that we have already cached the result of the query validation [as per your suggestion in October](https://gitter.im/sangria-graphql/sangria?at=59e883d301110b7231d5b212).

#### AWS testing

CPU usage

![cpu-05](https://user-images.githubusercontent.com/2237917/35363218-05707e40-01bd-11e8-944a-5991fabd13b2.png)

Garbage collection (note there are two different test runs included in the graph)

![gc](https://user-images.githubusercontent.com/2237917/35364270-4c1c2060-01c2-11e8-91db-704fda30acbf.png)

#### Local profiling

Hot spots
![hotspots](https://user-images.githubusercontent.com/2237917/35363234-117ed506-01bd-11e8-87c2-7fe3463ba3e8.png)

Hot spot drill down
![hotspotdrilldown](https://user-images.githubusercontent.com/2237917/35363259-27c2397a-01bd-11e8-8d78-9f32daed3afd.png)

Call tree
![calltree](https://user-images.githubusercontent.com/2237917/35363263-2eb49e44-01bd-11e8-88ed-81362e21097a.png)

Call tree - query parsing
![calltree-queryparsing copy](https://user-images.githubusercontent.com/2237917/35363268-38fedf2c-01bd-11e8-8829-b16f6225c0d9.png)

**Comment by OlegIlyenko** [comment]
Thanks a lot for sharing the profiling results and describing the test scenario! I will look at it in more detail.

At a first glance, looks like the profiling results hint on parsing, but you mentioned that the caching of parsing results does not affect the results. Maybe this is something worth investigating. As far as I remember, no parsing takes place during the actual execution, so it looks a bit unexpected.

There is also one known issue #296 with a specific query validation (`OverlappingFieldsCanBeMerged`). I think it might be a good idea to investigate it as well. I would suggest disabling either all validations or this specific validation and check whether it has an effect on the profiling results.

**Comment by alyssaBiasi** [comment]
Would caching the result of the validation be enough to remove it from the equation? For context, the tests were performed with a single query so each instance should only have been parsing and validating once at the beginning of the test run.

**Comment by OlegIlyenko** [comment]
You don't really need to cache the results of the validation. As soon as you have validated query once, you can disable the validation entirely since you already know whether the query is valid or not (you can also [validate query independently from the execution](http://sangria-graphql.org/learn/#query-validation)).

This approach is often used in the context of persisted queries, where the query is collected in advance (for example as a build step of a client application), validated and then stored somewhere on the server. Later on, the client can reference the query by ID and server don't need to validate it anymore since it was already verified.

**Comment by alyssaBiasi** [comment]
Hi @OlegIlyenko sorry for the slow response. We have just concluded some more testing.

We have managed to reduce CPU usage to below 70% \o/.

> You don't really need to cache the results of the validation. As soon as you have validated query once, you can disable the validation entirely since you already know whether the query is valid or not...

I'm afraid that isn't an option for us. Our Sangria API is multi-use and we will not know the queries required beforehand.

The steps we took to reduce CPU usage:

- Turned off validation in the `Executor`
- Added a cache that contains the result of both query parsing and validation at the query level before being passed to the `Executor`
- Implemented a `UserFacingError` trait for fields in the schema which require data be fetched from external resources
  - We were previously returning an exception here which resulted in many, many stack traces being printed by the [`ResultResolver`](https://github.com/sangria-graphql/sangria/blob/17abd0dedff20537e92c6e5cb019549c13531a6f/src/main/scala/sangria/execution/ResultResolver.scala#L128-L155). Due to the volume of data fetching errors, this turned out to be surprisingly expensive.

While we have managed to get this down to a somewhat acceptable level, profiling shows that resolution is still taking a considerable amount of time. I cannot think of a path forward to gain anymore improvements.

Should I open a separate issue to discuss the stack trace being printed within `ResultResolver`?

**Comment by OlegIlyenko** [comment]
Thanks for the update! Sure you can open a separate issue for error printing, but I would like to point out that it is just default behavior: it intentionally obfuscates the error message and prints the stack trace (for all unexpected errors) so that developer can see it since the library does not have a dependency on any logging framework. I would highly recommend you to always define `ExceptuonHandler` and do proper logging/message formatting in there: 

http://sangria-graphql.org/learn/#custom-exceptionhandler

With custom `ExceptuonHandler` you can (and expected to do it for a production application) avoid printing stack traces to a console.

**Comment by alyssaBiasi** [comment]
Thanks for you help!
