### ISSUE TITLE
Path dependent authorization with Sangria [Question]

### ISSUE THREAD

**Issue by ogroendal** [sangria-graphql/sangria#344]
We have an requirement where we need to authorize access to a field on an object based on what other objects the query previously passed through.

In the following example we want the first query to succeed and the second to fail, because in the first he queries the room through the house ( which he owns), and the second because he has not rights to the fields of (the same room) of the person with ID 1.

```
mutation { login(ownerOfHouse, pass) }

query {
	getHouse(id : 5) {
		room {
			size
		}
	}
}

query {
	getPerson(id : 1) {
		room {
			size
		}
	}
}
```

We also do not want it to matter if the person passes through multiple objects in the meantime.
Again in all examples it is the same room, we just want the query to pass through the house.

```
query {
	getHouse(id : 5) {
		occupant {
			id
			room {
				size
			}
		}
	}
}
```

We have tried simply keeping information on the previously resolved objects in a query in the Ctx of the query, and then updating the context with UpdateCtx.

**The problem**
 If we ask for a list - we want to update the context for each element of the list, so that any subqueries on that element remembers that the context passed that element. But how do we make an UpdatedContext for each sub element of the list? 

As an example of the list issue consider the following. For each house returned, we want the context to remember that we visited that particular house most recently, when asking the room for its size.

```
query {
	getHouses() {
		room {
			size
		}
	}
}
```

Is this an insane spec and an insane implementation? If yes the implementation is a bad idea, is there a more canonical way to approach this?

**Comment by OlegIlyenko** [comment]
> For each house returned, we want the context to remember that we visited that particular house most recently, when asking the room for its size.

Unfortunately, it is not possible at the moment to update the context in this way in the resolve function of `getHouses`. You can still do it in the resolver of `room` field, but I'm not sure whether it would be ok in your case. In general, I would try to avoid implicit path-context reslated dependencies. Maybe you can also try to be more explicit and if `Room` type has a dependency on the surrounding house, then you can define an ObjectType  in terms of `(House, Room)` (e.g. `ObjectType[MyCtx, (House, Room)]`). This would be a bit more explicit, but also less error-prone since all of the authorization within the `Room` type can be defined in terms of the explicitly available information (house and room).
