### ISSUE TITLE
Dependent queries and more "complicated" deferred value resolution

### ISSUE THREAD

**Issue by marcushg** [sangria-graphql/sangria#347]
Hi,

first of all - great project, even greater documentation. Not sure if this is too general for a question on sangria specifically, if so just let me know....
We are trying to rebuild a RESTful service in GraphQL using sangria as part of a larger evaluation. This service is in turn consuming two data sources and combining them to produce its results.

**Problem**
Let's use a very simplified example: We have Products with Prices - but not every product has a price (due to not being in stock or whatever)... e.g. ```case class Product(id: Int, name: String, category: String, price: Option[Price])``` and ```case class Price(productId: Int, price: Int)```
Our service allows you to search for product by e.g. category and only returns those products which in turn *have* a price - so very much like an INNER JOIN or intersection... And say, fetching `name` and `category` attributes is expensive so we don't want to fetch them for products *without* a price at all. Pseudo code of our current endpoint:
```
for {
    productIds <- fetch only the product ids from source A
    prices <- fetch prices for $productIds from source B
    products <- fetch remaining product attributes for $prices.productId from source A
} yield (products with prices combined)
```
So I see two problems we're trying to solve which go beyond simple attribute fetching from multiple sources:

1. dependent queries where the depending query may shrink the result set size (INNER JOIN/intersection)
1. 'efficient' (deferred) resolving / fetching of additional, more costly attributes

**Tried solutions**
-  Using [Deferred resolvers](http://sangria-graphql.org/learn/#deferred-value-resolution) and [Fetchers](http://sangria-graphql.org/learn/#high-level-fetch-api) to model the relation between `Product` and `Price` and allow for batching the `Price` fetches. Only partially solves 1. since it does not allow for shrinking the result set to only those product which have prices, which makes sense.
Could not really solve 2. without a lot of `Deferred` and `Future` trickery - which seemed hacky. Also I only need this optimization if the query requests the `price` as well and not just `name` or `category` attributes.
- Using [Batch executor](http://sangria-graphql.org/learn/#batch-executor) to create three dependent queries in one batch (one for each for-comprehension step). It was cool in that GraphQL is that flexible to form these kind of requests, but it felt wrong to expose those details to the client who shouldn't even know that `Product` and `Price` are coming from different data sources. Another problem is that the results of the first two intermediate queries is also returned while the client is ultimately interested in the result of the last query (`Product` with `Price` combined)

Thanks a lot and I am sure that I am missing something very simple here due to my unfamliar perspective on how to model and think in GraphQL.

**Comment by OlegIlyenko** [comment]
Do I understand it correctly: you would like to filter the the list of products based on the presence of the price. So, for instance, even for the following GraphQL query:

```graphql
{
  products(offset: 5200, limit: 100) {
    name
  }
}
```

the product list will not contain the products that do not have a price (which is verified with the help the service B)?

Considering that for bigger product dataset you would need the pagination and efficient filtering, doing the in-memory filtering might not be an option. In these cases I often denormalize the data for efficient data retrieval, filtering and pagination. In this case, for example, I would store the availability information in the product datastore (the propagation of this information might be eventually consistent, in most scenarios it is fine). 

I feel that this problem is not specific to GraphQL, but rather a data modeling and denormalisation issue. In general, I would suggest to do all of the filtering in the resolver of `products` field (which also includes the availability filter). The result might be just the list if product IDs or the list of product ID + price. in this scenario, You can just resolve name and category since you know that all these products will be included in the result.

**Comment by marcushg** [comment]
Regarding the first question - yes, you understand correctly that there wont be products without prices, maybe even no products at all.

Concerning data modeling and denormalization: Unfortunately this "service B" is external and kind of volatile/temporary in nature, i.e. prices exist at one time and might be different or gone the next time I query this same service, so I can't really sensibly "store"/denormalize those information in the product datastore. That's where the simplified example breaks down I guess ;-)

I tried to model it in a more general and declarative way using GraphQL than the very specific logic I had used in the current service itself. Anyways, in the mean time I resorted to sth similar to what you suggested in the last paragraph by fetching productIds and prices together and only then resolving the other attributes.

So thanks for the feedback and giving me another perspective on the problem....
