### ISSUE TITLE
Using MiddlewareFromScalar to convert to a different type

### ISSUE THREAD

**Issue by pulasthibandara** [sangria-graphql/sangria#368]
Hi, Thank you very much for this awesome library. I'v been enjoying working with `sangria-graphql` a lot.

### Scenario
I have a scenario, where I accept a input string type and try to convert it to a business domain type using utilities in the context.

My ScalarAlias looks something like this
```scala
val MetaOptionsType = ScalarAlias[MetaOptions, String](StringType, toScalar, fromScalar))
```

and I have implemented a middleware to create the MetaOptions type. 

### Problem
However the issue is, I have no way of implementing toScalar and fromScala methods. Casting to MetaOptions using `_.asInstanceOf[MetaOptions]` throws a runtime java error ` java.lang.String cannot be cast to MetaOptions`

### Current solution (hacky)
I've wrapped the string with a temporary wrapper that extends MetaOptions

```scala
case class WrapStringToMetaOptions(key: String) extends MetaOptions(null, null, null, null)

val MetaOptionsType = ScalarAlias[MetaOptions, String](StringType, _.toString, s => WrapStringToMetaOptions(s).asInstanceOf[MetaOptions]))
```

Is there a less hacky way of achieving this?

**Comment by OlegIlyenko** [comment]
At the moment `MiddlewareFromScalar` can't influence the scalar type. It's meant for more minor alterations of a scalar value (like encoding/decoding of strings). That said, I generally would suggest avoiding using `MiddlewareFromScalar` unless you absolutely need it, e.g. because the transformation depends on an external data obtainable only through context.

In your scenario, you can also define a small type hierarchy:

```scala
sealed trait MetaOptions

case class EncodedMetaOptions(s: String) extends MetaOptions
case class DecodedMetaOptions(a: Int, b: Boolean) extends MetaOptions
```

The scalar aliaz then can be defined like this:

```scala
val MetaOptionsType = ScalarAlias[MetaOptions, String](
  StringType, _.toString, s ⇒ Right(EncodedMetaOptions(s)))
```

I think it's a bit more type-safe.

**Comment by pulasthibandara** [comment]
Thanks, Yes this is definitely a more cleaner approach. Thank you @OlegIlyenko, I'll close this issue. Keep up the good work 👍
