### ISSUE TITLE
How can I create a custom Directive with DirectiveResolver?

### ISSUE THREAD

**Issue by daewon** [sangria-graphql/sangria#370]
I want to make the following directives - `@transform`

```graphql
{
  service {
    vertex(id: "daewon") {
      label(offset: 0, limit: 1) {
        vertex {
          name @transform(func: "(s) => s.toUpperCase")
        }
      }
    }
  }
}
```
To do this, I created a Directive and added it to the Schema as shown below.

In this case, I can not find a way to add a resolver for Directive.
Please let me know if there is a way.

```scala
val funcArg = Argument("func", StringType)
val Transform = Directive("transform",  arguments = List(funcArg),  locations = Set(DirectiveLocation.Field), shouldInclude = _ ⇒ true)

val schema = Schema(QueryType, None, directives = Transform :: BuiltinDirectives)
```

**Comment by daewon** [comment]
Thank you for your kind reply.

I solved the problem by using `astField` in each resolver for every field.
I will try to improve the direction by using `afterField`.

p.s: 
I would like to see the example below and have the feature.
I wonder why `Directive` does not include `Resolver`.

[graphql-custom-directives](https://github.com/lirown/graphql-custom-directives)
```graphql
query {
  input(value: "  foo bar   ") @trim @template(as:"${input} ${input}") @toUpper
}
// => { input: "FOO BAR FOO BAR" }
```

**Comment by OlegIlyenko** [comment]
Thanks for an example. I think graphql-custom-directives achieves it by rewriting every resolver in the schema with the help of `applySchemaCustomDirectives`. I believe that in sangria you can implement the same set of generic directives with the middleware.

I think directives do not have a resolver in the same way as fields do since they were originally intended to be used in a more broader scope especially on the query side. For example, directives like `@skip` and `@include` alter the graphql execution. So the directive definition are normally just describes the structural information, and it's behaviour and interpretation is defined elsewhere.
