### ISSUE TITLE
Using DeferredResolver with many Deferred types to avoid N+1 problem

### ISSUE THREAD

**Issue by Leromea** [sangria-graphql/sangria#376]
Hi there!

Just wondering if it is possible to use a custom DeferredResolver to deal with different types of Deferred objects, similar to this one here https://github.com/sangria-graphql/sangria/issues/63 but with many Deferred types.

Say I have two Deferred types:

```
case class DeferredTags(articleId: Int, args: Option[TagArgs]) extends Deferred[Seq[Tag]]
case class DeferredNotes(articleId: Int, args: Option[NoteArgs]) extends Deferred[Seq[Note]]
```

And my repository interface looks like this:

```
def getTags(articleIds: Seq[Int], args: Option[TagArgs] = None): Future[Seq[Tag]] = ???
def getNotes(articleIds: Seq[Int], args: Option[NoteArgs] = None): Future[Seq[Note]] = ???
```

What would my DeferredResolver look like? I am mostly stuck on the implementation of the resolve method, and how I should be returning the results.

Any links to code examples would be much appreciated!

Thanks,
Lero

**Comment by OlegIlyenko** [comment]
Sure, it is possible. In fact, this is also how high-level Fetch API is implemented. It is implemented as a `DeferredResolver` which can:

1. Group deferred values based on available fetchers
1. Load the deferred value data with the help of individual fetchers
1. Combine the loaded results in order that corresponds to the original order of deferred values

You can find the actual implementation in [`FetcherBasedDeferredResolver`](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/execution/deferred/FetcherBasedDeferredResolver.scala). The implementation might look a bit intimidating at first since it is quite generic. So I think it's better to first look at your example. 

In your scenario the deferred resolver will probably contain the same 3 steps:

1. Split deferred values in 2 groups - tags and notes
1. Load the data for these
1. Rearrange the results back so that loaded values are in the same order as original deferred values

Here is how it might look like:

```scala
class MyDeferredResolver extends DeferredResolver[MyCtx] {
  def resolve(deferred: Vector[Deferred[Any]], ctx: MyCtx, queryState: Any)(implicit ec: ExecutionContext) = {
    // step 1: Split deferred values in 2 groups - tags and notes
    val deferredTags = deferred.collect {case d: DeferredTags ⇒ d.articleId}
    val deferredNotes = deferred.collect {case d: DeferredNotes ⇒ d.articleId}

    // step 2: Load the data for these
    val loadedTags = getTags(deferredTags)
    val loadedNotes = getNotes(deferredNotes)

    // step 3: Rearrange the results back so that loaded values are in the same order as original deferred values
    deferred.map {
      case d: DeferredTags ⇒
        loadedTags.map(tags ⇒ tags.filter(_.articleId == d.articleId))

      case d: DeferredNotes ⇒
        loadedNotes.map(notes ⇒ notes.filter(_.articleId == d.articleId))
    }
  }
}
```

**Comment by Leromea** [comment]
That's perfect! Thanks a lot for the solution!
