### ISSUE TITLE
Add additional items to per-request cache

### ISSUE THREAD

**Issue by sachee** [sangria-graphql/sangria#377]
Currently, Sangria supports caching per request by using `Fetchers.caching`. This is great, however in some cases, it would be nice to "manually" cache items from responses.

This is especially useful when migrating from legacy systems or when GraphQL is interacting with services that the developer might _not_ be able to change.

Say we query for a `post`:
```graphql
{
  post(id: "abc123456") {
    title
    user {
      name
    }
  }
}

```
and Sangria looks up that post by making a REST request, for example: http://my.api.com/post/abc123456.

The service that returns a `post` for us also automatically returns the `user` who wrote that post:
```json
{
  "post": {
    "title": "A New Hope",
    "userId": "def34567"
  },
  "user": {
    "name": "Luke",
    "userId": "def34567"
  }
}
```
Normally, we would get the `post` data back, see we have a `userId`, and then fetch the `user` using that `userId`. However, in this case that would mean an extra round trip, and this endpoint happens to already return the `user` for us. (Perhaps for this service, it's really fast to look up the `user`, so it's done automatically for us).

In this scenario, it would be great if when we get the result back that includes the `user`, we were able to add the `user` to our Sangria per-request cache, in addition to the `post`. This would mean we wouldn't need to make an additional call to get the `user` as we already got the `user` info when we got the `post` response.

This would be a great tool for interoperating with REST-like services that return "related data" in their responses, because we could keep the resolver implementations simple, yet optimize them by manually populating the cache from "related data responses" when applicable.

**Comment by OlegIlyenko** [comment]
Thanks for a detailed description! I think it would be a good addition to a library.

I drafted initial implementation. I would appreciate if you could look at the example of the new API and give your feedback.

My suggestion is to provide more information to a fetcher via the first argument (so instead of `Ctx`, fetcher will get `FetcherContext[Ctx]` with some additional info including caches). For your example, fetchers might look like this:

```scala
val userFetcher = Fetcher.cachingWithContext[MyCtx, User, String](...)

val postFetcher =
  Fetcher.cachingWithContext[MyCtx, Post, String] { (c, ids) ⇒
    c.ctx.loadPosts(ids).map { postsData ⇒
      // populate user cache
      c.cacheFor(userFetcher).foreach(userCache ⇒
        postsData.foreach (postData ⇒ 
          userCache.update(postsData.user.id, postsData.user)))

      postsData.map(_.post)
    }
  }
```

More complete example can also be found in the test: https://github.com/sangria-graphql/sangria/commit/4c915dad324af8c9afe0ffb7a8914c1e4d2c32c3#diff-b97ff02b892879bd7d0356c39fad0815

What do you think about this approach? Will it work for you?

**Comment by sachee** [comment]
Thanks for such a quick response and well thought out implementation. Ya, this looks great! I think this will work fine for us! 🎉
