### ISSUE TITLE
Question: Recommended way to integrate with Apollo Client Subscriptions

### ISSUE THREAD

**Issue by rajamony** [sangria-graphql/sangria#391]
Sangria is a fantastic piece of work - thank you for all the effort that has gone into it.

Our backend uses Sangria and we would like to connect it to an Apollo GraphQL client. Apollo uses websockets for subscriptions and I am wondering if there are any recommendations for how to integrate Sangria against the Apollo websocket protocol, as described here: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

**Comment by paulpdaniels** [comment]
@rajamony this may not be totally what you are looking for but the solution that we are going with, and one that was recommended by the apollo guys is to use an Apollo-Server instance in front of your sangria app and use Apollo-Server to stitch together the schemas.

**Comment by OlegIlyenko** [comment]
In general, Apollo subscription protocol is one layer above GraphQL/Sangria. So it should be possible to implement it on HTTP layer with libraries like akka-http and play. I know several projects (like [Prisma](https://github.com/prismagraphql/prisma/)) that have implemented Aplollo protocol in a sangria app. The is also [an example application available](https://github.com/sangria-graphql/sangria-subscriptions-example) that shows how to implement GraphQL subscriptions with sangria. It does not implement apollo-specific protocol, but the approach would be quite similar.

As far as I'm aware, at the moment there no library that provides out-of-the-box integration between let's say `circe` + `akka-http` + `sangria` + `apollo-subscription-protocol`. I think one of the main reasons is that in scala there is a lot of diversity of HTTP and JSON libraries in scala ecosystem. It would hard to write a library that would satisfy everybody (e.g. some people use spray-json + akka-http, but some might use circe + http4s, etc.). That said, if you are working with a specific HTTP library and would like to implement apollo subscription protocol, I would like to encourage you to extract generic integration part in a small library. I think a lot of people will appreciate this.

I think @paulpdaniels pointed out a valid approach as well. Though I generally prefer avoiding unnecessary proxies and intermediate servers. There are definitely scenarios where this approach might be beneficial. But in general case I would recommend to implement apollo protocol as a part of your scala application (or maybe as a separate scala app since WebSockets often need special handling in terms of the server lifecycle, deployment, etc.).
