### ISSUE TITLE
Lazy Union Type definition

### ISSUE THREAD

**Issue by srenault** [sangria-graphql/sangria#402]
I'm currently working on an app where I'm generating on the fly a graphql schema from dynamic data.
The entities I define inherit from an `EntityInterface` and can reference each others through a `Link` field.  

Where the complexity comes from is, a `Link` can point to either an `EntityInterface`, or a `FooType` or a `BarType` (where `FooType` and `BarType` are well known defined type).
My first attempt to define the `Link` type was defining it as an Interface.
So I had my `EntityInterface`, `FooType` and `BarType` extending the `Link` interface.
What was weird with this solution is, my entities became a `Link` with some inherited attributes I didn't want to have.

My second attempt was using the Union Type. I first tried defining `Link` as: 
```
type Link = FooType | BarType | EntityInterface
```
But there is no way using Interfaces here.
For my use case, I think the only solution would be referencing all the entity types I generate like:
```
type Link =  FooType | BarType | EntityA | EntityB | EntityC ...
```
But at the time of defining the Link type, I don't know yet the full entity types.
What do you think about making the Union Type definition lazy?

```scala
case class UnionType[Ctx](
    types: => List[ObjectType[Ctx, _]],
    ....
}
```
Hopping it's clear enough.

Thanks for your work!

**Comment by srenault** [comment]
@OlegIlyenko Tell me if you want I detail more.

**Comment by OlegIlyenko** [comment]
Thanks for a detailed description. I think this indeed might be a good addition to a library. In case of recursive type definitions we need to provide a lazy initialization for the list of types in a union.

By-name parameter will not work in this case since it is a cae class field, but we can redefine it as a no-arg function (e.g. `types: () ⇒ List[ObjectType[Ctx, _]]`). We would also need to provide some factory methods in a companion object to provide backwards compatibility, so that we can also keep eager alternative.

Would you like to work on a PR for this?

**Comment by srenault** [comment]
Okey, I'm going to work on this.

**Comment by nickhudkins** [comment]
@srenault out of curiosity... do you have any work that has been done on supporting lazy types in union types?

**Comment by nickhudkins** [comment]
One more shot! @srenault was this something you had started work on?

**Comment by nickhudkins** [comment]
Supported :)
