### ISSUE TITLE
InternalServerError returns 200

### ISSUE THREAD

**Issue by limdauto** [sangria-graphql/sangria#416]
I'm following the instruction in the [doc](https://sangria-graphql.org/learn/#error-handling) as well as in a [related issue](https://github.com/sangria-graphql/sangria/issues/405) to execute my query as follow:

```
    Executor.execute(
      schemaDefinition,
      query,
      context,
      variables = vars,
      operationName = operation
    ).map(OK -> _)
      .recover {
        case error: QueryAnalysisError => BadRequest -> error.resolveError
        case error: ErrorWithResolver => InternalServerError -> error.resolveError
      }
```

The `BadRequest` returns 400 as expected. However, `InternalServerError` returns a 200 with the response body:

```
{"data":null,"errors":[{"message":"Internal server error","path":["hello"],"locations":[{"line":1,"column":3}]}]}
```

Is this expected?

Thanks.

**Comment by OlegIlyenko** [comment]
I is most probably caused by exception in the resolve function of `hello` field. You also need to define a [custom exception handler](https://sangria-graphql.org/learn/#custom-exceptionhandler) to handle these.

**Comment by limdauto** [comment]
Thank you. I guess that's what I'm trying to say. Is it intentional that un-handled exceptions will result in a 200?

**Comment by OlegIlyenko** [comment]
In general yes. If you want, you can use [extended execution scheme](https://sangria-graphql.org/learn/#alternative-execution-scheme), get the list of exceptions and use different status code for the whole response if there are any. But in general in these scenarios result of the execution is partially successful (some of the fields were executed successfully and gave some good values) and partially failed (e.g. some other fields have thrown exception). So there is no single HTTP status to represent such results. Most of the GraphQL servers return 200 in these situations since error information as well as error propagation rules are well defined in the spec and the list of errors available in the response together with the successfully resolved data. But it is up to you how you would like to handle the HTTP code in this scenario.

**Comment by limdauto** [comment]
Cheers. Thank you for explaining.
