### ISSUE TITLE
sangria.relay.Connection[B] is invalid type for the resulting GraphQL type Option[A].

### ISSUE THREAD

**Issue by MeerKatDev** [sangria-graphql/sangria#459]
I am having troubles understanding the error message:

```
def authorizedListField[A, B <: SangriaNode](name: String, optType: OutputType[A], rslv: MainContext => List[B]): Field[SecureContext, SourceQuestion] =
    Field(name, OptionType(optType), arguments = Connection.Args.All,
      resolve = { ctx => ctx.ctx.authorised(sourceQuestions) { _ =>
        Connection.connectionFromSeq(rslv(ctx), ConnectionArgs(ctx))
      }})
```

I abstracted this away from a method, and I don't really get why in this case it doesn't work. I suppose some problem with the syntax, but I can't see where.

EDIT: I'm trying to generalize the function here:
https://github.com/sangria-graphql/sangria-relay/blob/master/src/test/scala/sangria/relay/ConnectionSpec.scala
at line 47. I can't get what to put as the rslv function return type.

**Comment by paulpdaniels** [comment]
You’re resolver is returning a Connection of B but you are marking the field as an Option of A.

**Comment by MeerKatDev** [comment]
I see that, so how do I instruct the function to return a Field type instead? I miss what to put in that "List[B]" I think

**Comment by nickhudkins** [comment]
Hi @MeerKatDev, without seeing your code I am not sure that we can help out, but if I had to guess:

`ctx.ctx.authorised(sourceQuestions)` returns an `Option[A]`, rather than a `Connection[B]`. Without seeing the implementation of `authorised`, I am afraid we could not help. Additionally, this is a Scala specific question and unrelated to Sangria, so I'm going to go ahead and close it. If you still are experiencing trouble, you may want to hop in Gitter to discuss.
