### ISSUE TITLE
Fetcher for non primary key arguments

### ISSUE THREAD

**Issue by rolandjohann** [sangria-graphql/sangria#514]
We want to query sub resources of Entities that get filters passed, like am `Interval` of creation dates. As those dates are not part of the actual entity I can't get a working solution for a fetcher implementation as the `HasId` type class requires to generate an Id to match the input and the date interval can't derived from the entity.

The query looks like this:

```graphql
query OrdersByCustomerGroup {
  customerGroup(id: 58) {
    id
    name

    standardOrders(interval: "2020-01-01/2020-09-30") {
      id
      portions
    }
  }
}
```

*fetcher*
```scala
  val fetcher2 = Fetcher { (ctx: AppContext, ids: Seq[(Interval, Long)]) =>
    ctx
      .standardOrderService
      .listByIntervalAndCustomerGroupId(ids.toList)
  }(HasId(x => (new Interval(DateTime.now(), DateTime.now()), x.customerGroupId)))
```

*usage of fetcher*
```scala
      Field("standardOrders",
        ListType(StandardOrderSchema.ObjectType),
        arguments = IntervalArg :: Nil,
        resolve = c => StandardOrderSchema.fetcher2.deferSeqOpt(Seq(c.arg(IntervalArg) -> c.value.id))
      ),
```

**Comment by nickhudkins** [comment]
Hey @rolandjohann! Based on the query you have here, a fetcher may not even be helpful, unless you have a scenario in which `standardOrders` can be queried for on a field with (n) results.

Based on the query you have here, it appears that `n=1` since you are asking for a single customer group by ID.

So the first thing I would look at is "Can I just get rid of the fetcher?"

If you DO have an `n+1` problem, then I would look at calculating what interval each response falls within. Some pseudo code:

```scala
case class StandardOrder(orderPlaced: LocalDate, id: String) {
  // Something along these lines...
  def identifyingInterval(intervals: List[Interval]) = intervals.find(_.start <= orderPlaced && _.end >= orderPlaced)
}


// Multiple intervals
val ids = List(
  Interval(start="2020-01-01", end="2020-02-02"),
  Interval(start="2030-01-01", end="2030-02-02")
)

// All matching entries
List(
  StandardOrder(orderPlaced = "2020-01-01", id: 1),
  StandardOrder(orderPlaced = "2030-02-02", id: 1)
)

// Your 'HasId'
HasId(x => (x.identifyingInterval(ids), x.customerGroupId))

```
