### ISSUE TITLE
200 OK for all kind of response

### ISSUE THREAD

**Issue by nsisodiya** [sangria-graphql/sangria#524]
May be it sound stupid, but I am curious to know how to send `all response` with 200 OK all the times?
Example - In the case of BadRequest, instead of 400, the status code can be 200 OK and errors are already there as JSON data.
I find writing generic frontend code is much easy when the HTTP status code is 200 OK all the time. GraphQL has error's array in response json which is sufficient.

**Comment by nickhudkins** [comment]
This is somewhat specific to your server implementation but if you take a look at the `sangria-akka-http-example` you can see here:

https://github.com/sangria-graphql/sangria-akka-http-example/blob/master/src/main/scala/Server.scala#L36-L40

```scala
		executeGraphQlRequest(/**/)
        .map(OK -> _)
        .recover {
          case error: QueryAnalysisError => BadRequest -> error.resolveError
          case error: ErrorWithResolver => InternalServerError -> error.resolveError
        })
```

In this case, any successful completion returns a 200 and the result of `executeGraphQLRequest`, otherwise (in the `recover` block) the example is matching on two types of errors, and chosing to provide a 400 / 500 for BadRequest / Unhandled.

If you truly would like to override this behavior, you would want to no-longer pattern match on those errors, and you could provide the same `OK -> _` tuple in `recover` like so:

```scala
		executeGraphQlRequest(/**/)
        .map(OK -> _)
        .recover(OK -> error.resolveError)
```

@nsisodiya Hope this helps!

**Comment by nsisodiya** [comment]
@nickhudkins Thanks a lot.
