### ISSUE TITLE
Implement CirceJsonSupport in order to be able to integrate with Circe

### ISSUE THREAD

**Issue by schrepfler** [sangria-graphql/sangria#58]
Circe is an up and coming JSON library for Scala based on Cats https://github.com/travisbrown/circe

**Comment by OlegIlyenko** [comment]
I thought about it, and decided to implement circe support now, since it's pretty different from others, so it help to validate abstractions I built for json support. I just released it in v0.3.1. Argonaut need to wait though - it does not support big decimals yet, which is required for sangria. But looks like they already implemented it in upcoming v6.1.
