### ISSUE TITLE
Identical documents should be equal

### ISSUE THREAD

**Issue by jvliwanag** [sangria-graphql/sangria#75]
The following should pass:

```
assert(QueryParser.parse("{id}") == QueryParser.parse("{id}"))
```

In line with this, is there an equivalence relationship between `{id,}` and `{id}`?

**Comment by OlegIlyenko** [comment]
You are right for identical queries `equals` should return `true`. Nasty `sourceMapper` messed things up :)

About difference between `{id,}` and `{id}`: in this particular example `equals` will return `true`. But in general AST for differently formatted queries will not be equal. Like in this example:

https://github.com/sangria-graphql/sangria/blob/01bc12c96c75b3c0267c315ebc168299f2b885b0/src/test/scala/sangria/parser/QueryParserSpec.scala#L429

The reason for this is the position of AST nodes. In order to provide helpful error messages, AST needs to save it's position in the source query. There is a helpful method available on all AST nodes: `withoutPosition` makes a deep copy of an AST without position

**Comment by jvliwanag** [comment]
Awesome. Thanks!
