### ISSUE TITLE
Best way to parse input?

### ISSUE THREAD

**Issue by luisobo** [sangria-graphql/sangria#92]
Hi there,

I was wondering what is the best way to parse input objects. We provide the schema of this objects with InputObjectType, the problem is that these InputObjectTypes are not associated with any Scala type. all we get in the resolve function in the list of Args.  that we have to manually downcast to the right types, even tho the checking as been done already by the query parser.

Is there any way, or would it make sense to have it, to extract case classes out of args?

For example:
```scala
SomeInput(hello: String, bye: Int)
```
then
```scala
resolve = ctx => ctx.args[SomeInput]("input")
```

Thanks!

**Comment by OlegIlyenko** [comment]
At the moment the input objects are parsed in the `Map[String, Any]` data structure. This is temporary though. I already working on better solution for this. I track the progress in this issue: https://github.com/sangria-graphql/sangria/issues/37

Ideally, when it's done, it will work very similar to what you have described (and it's the current plan). I would like to implement a type-class based deserialization mechanism, something that I already started with https://github.com/sangria-graphql/sangria/issues/68. I would like to introduce `FromInput` type-class as a counterpart of `ToInput` introduced in that issue.

Since there are already a lot of library support for the json deserialization in other libraries and people probably already have some type-classes around to de/serialize their domain model from/to json, I would like to integrate it with type-classes from existing Json libraries. So for instance if you already have play's `Reads` or spray-json's `JsonFormat` defined, then `ctx.args[SomeInput]("input")` should work out-of-the-box. This mechanism already works for `ToInput` type-class.

What do you think about this approach?

**Comment by luisobo** [comment]
Seems awesome to me. So, is this doable already as per #68?

**Comment by OlegIlyenko** [comment]
https://github.com/sangria-graphql/sangria/issues/68 only used for a default values of field and directive arguments, so it does not help a much with the input object deserialization. `FromInput` (which is meant for input object deserialization) is still work in progress, so it's not available yet.

**Comment by luisobo** [comment]
Gotcha, thank you
